/* ============================================
   ACOSTEL — Datos del catálogo
   ------------------------------------------------
   Este es el ÚNICO archivo que hay que tocar para
   agregar, editar o quitar propiedades y vehículos.

   Cada ficha es un bloque { ... } dentro del arreglo
   `listings`. Copia un bloque existente, pégalo,
   cambia el "id" (debe ser único) y actualiza los
   demás datos.

   type: "propiedad" o "vehiculo"
   images: lista de rutas a fotos. Mientras no haya
   fotos reales, se usan las imágenes de marcador
   images/site/placeholder-propiedad.svg o
   images/site/placeholder-vehiculo.svg

   video (opcional): agrega esta línea a cualquier ficha
   para mostrar un video. Al pasar el mouse sobre la
   tarjeta (o mantener presionado en el celular) se
   reproduce una vista previa; en la ficha aparece un
   reproductor completo. Acepta dos formas:
     video: "https://www.youtube.com/watch?v=XXXXXXXXXXX"
     video: "images/listings/veh-001.mp4"
   Para videos largos (recorridos completos) se recomienda
   subirlos a YouTube como "no listado" y pegar el link acá,
   en vez de subir el archivo de video directo al repositorio.
   ============================================ */

const listings = [
  // ---------------- PROPIEDADES ----------------
  {
    id: "prop-copa-2",
    type: "propiedad",
    title: "Lote 2 - Copapayo",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "LOTE EN VENTA – COPAPAYO. Zona con plusvalía y fácil acceso. Ideal para casa de descanso o proyecto familiar. Área: 842.5 m² / 1,205.47…",
    description:
      "LOTE EN VENTA – COPAPAYO. Zona con plusvalía y fácil acceso. Ideal para casa de descanso o proyecto familiar. Área: 842.5 m² / 1,205.47 vrs². Servidumbre privada. Energía eléctrica. Agua potable. Cerca del río. Precio: $29,000",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-clou",
    type: "propiedad",
    title: "Casa José",
    price: 77000,
    location: "Colón",
    badge: "Destacada",
    operacion: "Venta",
    summary: "CASA NUEVA A ESTRENAR — LOURDES COLÓN Colonia Las Margaritas, Lourdes Colón, La Libertad Oportunidad ideal para quienes buscan un hogar…",
    description:
      "CASA NUEVA A ESTRENAR — LOURDES COLÓN Colonia Las Margaritas, Lourdes Colón, La Libertad Oportunidad ideal para quienes buscan un hogar moderno, nuevo y bien ubicado — a solo 5 minutos de Metrocentro Lourdes. LA PROPIEDAD Terreno de 161 m² (7 × 23 m / 230 v²) 3 habitaciones amplias · 1 baño completo Sala espaciosa + cocina moderna · Cochera techada Agua y luz ya instaladas · Acceso desde dos calles PRECIO: $77,000 — se aceptan trámites bancarios, fondo social y contado",
    specs: {
      habitaciones: 3,
      banos: 1,
      areaConstruccion: "—",
      areaTerreno: "161 m² / 230 v²",
      parqueos: "2",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-lour1",
    type: "propiedad",
    title: "Residencial El Conacaste — Casa nueva a estrenar",
    price: 195000,
    location: "Colón",
    badge: "Destacada",
    operacion: "Venta",
    summary: "CASA COMPLETAMENTE NUEVA A ESTRENAR EN LOURDES COLÓN Exclusividad, comodidad y plusvalía en un solo lugar. Diseñado para quienes buscan…",
    description:
      "CASA COMPLETAMENTE NUEVA A ESTRENAR EN LOURDES COLÓN Exclusividad, comodidad y plusvalía en un solo lugar. Diseñado para quienes buscan vivir con tranquilidad, privacidad y estilo.",
    specs: {
      habitaciones: 3,
      banos: 2,
      areaConstruccion: "—",
      areaTerreno: "300 m² / 429 v²",
      parqueos: "2",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-atac4",
    type: "propiedad",
    title: "Terreno Ataco 16x65m",
    price: 185000,
    location: "Ataco",
    operacion: "Venta",
    summary: "SE VENDE PRIVILEGIADO TERRENO A ORILLA DE CALLE EN ATACO A 30 METROS DEL RESTAURANTE LA PAMPA ATACO IDEAL PARA NEGOCIO, DESAROLLO VERTICAL,…",
    description:
      "SE VENDE PRIVILEGIADO TERRENO A ORILLA DE CALLE EN ATACO A 30 METROS DEL RESTAURANTE LA PAMPA ATACO IDEAL PARA NEGOCIO, DESAROLLO VERTICAL, ENTRE OTROS RUBROS. ZONA DE ALTA DEMANDA Y ALTA PLUS VALÍA . TERRENO PLANO CON FACTIBILIDAD DE LUZ ELECTRICA Y AGUA POTABLE. 16 METROS DE ANCHO POR 75 METROS DE LARGO CON DOBLE ACCESO PARA HACER UN PARQUEO ANEXO ATRAS DE LA PROPIEDAD . INCOMPARABLE OPORTUNIDAD DE INVERSION ! SU VALOR ES DE $185.000 DÓLARES A UN SUPER PRECIO FIJO NO NEGOCIABLE VENTA CASH O POR MEDIO DE BANCOS .",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,200 m² / 1,717 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-occi",
    type: "propiedad",
    title: "Condominio - Occidente",
    price: 450000,
    location: "Santa Ana",
    operacion: "Venta",
    summary: "SE VENDE MINI CONDOMINIO DE 10 HABITACIONES EN LA ZONA DE OCCIDENTE. SON 10 HABITACIONES CON SU PROPIO BAÑO COMPLETO . AREA DE LAVANDERIA…",
    description:
      "SE VENDE MINI CONDOMINIO DE 10 HABITACIONES EN LA ZONA DE OCCIDENTE. SON 10 HABITACIONES CON SU PROPIO BAÑO COMPLETO . AREA DE LAVANDERIA INDEPENDIENTE . ENERGIA ELECTRICA Y AGUA POTABLE. ACTUALMENTE TODAS LAS HABITACIONES ALQUILADAS EN $ 130 USDS MENSUALES CADA UNA ( PRECIO JUSTO ) UNA DE LAS VENTAJAS ES QUE SI USTED COMO INVERSIÓNISTA DESEA HACERLE SEGUNDO NIVEL A CADA HABITACION EL PRECIO AUMENTARIA . COLONIA SAN JOSÉ SE UBICA CARRETERA A METAPAN ANTES DE LLEGAR A SANTA ANA NORTE . SUS MEDIDAS SU 11 METROS DE ANCHO POR 42 METROS DE LARGO . SE PUEDEN ESTACIONAR EN LINEA HASTA 5 VEHICULOS. LA PROPIEDAD GENERA EN SU TOTALIDAD $ 1200 DÓLARES MENSUALES . SU VALOR DE VENTA ES DE $450.000 DÓLARES.",
    specs: {
      habitaciones: 10,
      banos: 10,
      areaConstruccion: "—",
      areaTerreno: "462 m² / 661 v²",
      parqueos: "5",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-atac3",
    type: "propiedad",
    title: "Finca de 17Mnz - Ataco",
    price: 260000,
    location: "Ataco",
    operacion: "Venta",
    summary: "SE VENDE FINCA DE 17 MANZANAS EN ATACO SE DIVIDE EN 3 UBICACIONES EN UN RADIO DE 300 A 500 METROS A LA REDONDA . SE SITÚA A 10 MINUTOS DEL…",
    description:
      "SE VENDE FINCA DE 17 MANZANAS EN ATACO SE DIVIDE EN 3 UBICACIONES EN UN RADIO DE 300 A 500 METROS A LA REDONDA . SE SITÚA A 10 MINUTOS DEL PUEBLO . 1200 METROS SOBRE EL NIVEL DEL MAR . CUENTA CON SU CASA PATRONAL . SE NECESITA VEHICULO 4X4 PARA ACCESAR A LA PROPIEDAD TOPOGRAFIA PLANA Y SEMIPLANA SU VALOR ES DE $ 260.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "118,779 m² / 170,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-cang",
    type: "propiedad",
    title: "Terreno Cangrejera",
    price: 38000,
    location: "Cangrejera",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EN CANGREJERA A 700 METROS DE DISTANCIA DE LA PLAYA . MEDIDAS DE 12.96 DE ANCHO POR 27 METROS DE LARGO 349 METROS² PLANO…",
    description:
      "SE VENDE TERRENO EN CANGREJERA A 700 METROS DE DISTANCIA DE LA PLAYA . MEDIDAS DE 12.96 DE ANCHO POR 27 METROS DE LARGO 349 METROS² PLANO IDEAL PARA HACER UNA CASA O RANCHO DE PLAYA SU VALOR ES DE $38.000 DÓLARES FIJOS",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "349 m² / 499 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-copa2",
    type: "propiedad",
    title: "Terreno Copapayo Armenia",
    price: 62000,
    location: "Armenia",
    operacion: "Venta",
    summary: "SE VENDE TERRENO UBICADO EN COPAPAYO ARMENIA. A TAN SOLO 4 MINUTOS DELA CARRETERA. CON 3 ACCESOS DE ENTRADA. UNA CON ACCESO A CLAUDIA LARS.…",
    description:
      "SE VENDE TERRENO UBICADO EN COPAPAYO ARMENIA. A TAN SOLO 4 MINUTOS DELA CARRETERA. CON 3 ACCESOS DE ENTRADA. UNA CON ACCESO A CLAUDIA LARS. EXCELENTE UBICACION. ACCESO EN CUALQUIER VEHÍCULO. CALLE DE TIERRA PLANO. MEDIDA 18 METROS DE FRENTE POR 46 METROS DE FONDO. TERRENO TOTALMENTE PLANO CON ENERGÍA ELECTRICA Y AGUA. SOLO DE ACTIVARLA. TIERRA TOTALMENTE FERTIL. SE LLEGA SIN DIFICULTAD. SU PRECIO ES DE $ 62.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "828 m² / 1,185 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-bazz",
    type: "propiedad",
    title: "Terreno Blvd Bazzini",
    price: 95000,
    location: "Blvd. Bazzini",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EXCELENTE UBICACION VISTA ESPECTACULAR SOBRE BOULEVARD BAZINI. CERCA DESVIO HACIENDA TRANSITO A 4 MUNUTOS DESVIO TALNIQUE,…",
    description:
      "SE VENDE TERRENO EXCELENTE UBICACION VISTA ESPECTACULAR SOBRE BOULEVARD BAZINI. CERCA DESVIO HACIENDA TRANSITO A 4 MUNUTOS DESVIO TALNIQUE, JAYAQUE Y ATEOS. A 1 MINUTO DE CARRETERA BAZINI A 10 MINUTOS DE ESCUELAS, CENTROS COMERCIALES, Y NEGOCIOS DE LOURDES. IDEAL PARA PROYECTO DE CABAÑAS, CASA DE CAMPO, LUGAR DE RETIRO ETC. CALLE DE INGRESO PLANA MEDIDA DE LAS 2 PARCELAS TOTAL ES 2,500 M² TERRENO SEMI PLANO ACCESO EN CUALQUIER VEHÍCULO. TIERRA TOTALMENTE FERTIL. SE LLEGA SIN DIFICULTAD. SU VALOR ES DE $ 95.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,500 m² / 3,577 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-copa-p",
    type: "propiedad",
    title: "Lote Premium (con pozo) - Copapayo",
    price: 32000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "LOTE PREMIUM EN VENTA – COPAPAYO Excelente ubicación y fácil acceso. Lote con ventaja sobre los demás, ideal para vivienda o inversión.…",
    description:
      "LOTE PREMIUM EN VENTA – COPAPAYO Excelente ubicación y fácil acceso. Lote con ventaja sobre los demás, ideal para vivienda o inversión. Área: 842.5 m² / 1,205.47 vrs² Pozo propio incluido, acceso por ambos extremos, colinda en su parte más larga con la servidumbre, energía eléctrica disponible, agua potable, entorno natural cerca del río. Precio: $32,000",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-ssal2",
    type: "propiedad",
    title: "Terreno 598m2 SS",
    price: 198000,
    location: "San Salvador",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EN SAN SALVADOR. TERRENO DE 598 mts = 856 v2 CUENTA CON EL SERVICIO DE AGUA POTABLE Y LOS POSTES DE ALUMBRADO ELÉCTRICA SE…",
    description:
      "SE VENDE TERRENO EN SAN SALVADOR. TERRENO DE 598 mts = 856 v2 CUENTA CON EL SERVICIO DE AGUA POTABLE Y LOS POSTES DE ALUMBRADO ELÉCTRICA SE PUEDE ACCEDER POR 2 LADOS . INGRESANDO POR EL EX RESTAURANTE LA HERRADURA Y TAMBIEN POR LA 75 AVENIDA NORTE SU VALOR ES DE $198.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "598 m² / 856 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-ahua2",
    type: "propiedad",
    title: "Casa Grande en Venta - Ahuachapan",
    price: 560000,
    location: "Ahuachapán",
    operacion: "Venta",
    summary: "SE VENDE PROPIEDAD DE LUJO Y AMPLIAS INSTALACIONES EN AHUACHAPAN A POCOS METROS DEL PARQUE CONCORDIA CONSTA DE 6 AMPLIAS HABITACIONES - 6…",
    description:
      "SE VENDE PROPIEDAD DE LUJO Y AMPLIAS INSTALACIONES EN AHUACHAPAN A POCOS METROS DEL PARQUE CONCORDIA CONSTA DE 6 AMPLIAS HABITACIONES - 6 BAÑOS - PISCINA - DECK - TERRAZA Y UN AMPLIO JARDIN - 2 SALAS DE ESTAR - SALA COMEDOR - COCINA - DESAYUNADOR Y ESPACIO PARA 2 VEHICULOS SU VALOR ES DE $560.000 DÓLARES PERSONAS INTERESADAS EN COMPRAR Y AGENDAR UNA VISITA FAVOR CONTACTARCE",
    specs: {
      habitaciones: 6,
      banos: 6,
      areaConstruccion: "—",
      areaTerreno: "—",
      parqueos: "2",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-cumb",
    type: "propiedad",
    title: "Terreno - Cumbres de la escalón",
    price: 1449250,
    location: "Cumbres de la Escalón",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EN LA ZONA MAS EXCLUSIVA Y DE GRAN PLUSVALÍA . CUMBRES DE LA ESCALÓN EN SAN SALVADOR . TERRENO URBANO LISTO PARA CONSTRUIR…",
    description:
      "SE VENDE TERRENO EN LA ZONA MAS EXCLUSIVA Y DE GRAN PLUSVALÍA . CUMBRES DE LA ESCALÓN EN SAN SALVADOR . TERRENO URBANO LISTO PARA CONSTRUIR . CASA GRANDE , TORRE DE APARTAMENTOS PARA DESAROLLO VERTICAL 2.635 VARAS² TOPOGRAFIA PLANA TERRENO URBANO CON FACTIBILIDAD DE LUZ ELECTRICA Y AGUA POTABLE SU VALOR TOTAL ES DE $1.449.250 UN MILLON CUATROCIENTOS CUARENTA Y NUEVE MIL DÓLARES Y SU VALOR POR VARA ES A $550.00 USDS LA VARA² SI HACE UN ANALISIS DEL VALOR . ES MENOR ACTUALMENTE AL DEL VALOR DE MERCADO .",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,842.16 m² / 2,635 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-sanv",
    type: "propiedad",
    title: "215Mnz - San Vicente Canton rio frio",
    price: 1720000,
    location: "San Vicente",
    operacion: "Venta",
    summary: "SE VENDEN 215 MANZANAS EN SAN VICENTE . EN RIO FRIO A 200 METROS DE LA CARRETERA PRINCIPAL DE ESTA PROPIEDAD SE PUEDEN EXTRAR PIEDRA , LAJA…",
    description:
      "SE VENDEN 215 MANZANAS EN SAN VICENTE . EN RIO FRIO A 200 METROS DE LA CARRETERA PRINCIPAL DE ESTA PROPIEDAD SE PUEDEN EXTRAR PIEDRA , LAJA Y ENTRE OTROS MINERALES CON FACTIBILIDAD DE AGUA Y LUZ ELÉCTRICA TOPOGRAFIA SEMIPLANA ACCESO EN CUALQUIER VEHÍCULO IDEAL PARA GANADERIA Y CULTIVO LA PROPIEDAD CUENTA CON 2 RIOS DENTRO EN UNA EXCELENTE UBICACIÓN SU VALOR ES DE $8000 DÓLARES POR MANZANA LA VENTA ES TOTAL Y DE UN SOLO PAGO NO EXISTE CREDITO .",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,502,205 m² / 2,150,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-ssal",
    type: "propiedad",
    title: "Propiedad en SS",
    price: 285000,
    location: "San Salvador",
    operacion: "Venta",
    summary: "SE VENDE EXCELENTE PROPIEDAD EN SAN SALVADOR. A ORILLA SE CALLE Y GENERANDO INGRESOS MENSUALES 840 metros cuadrados Consta de: 5…",
    description:
      "SE VENDE EXCELENTE PROPIEDAD EN SAN SALVADOR. A ORILLA SE CALLE Y GENERANDO INGRESOS MENSUALES 840 metros cuadrados Consta de: 5 habitaciones alquiladas actualmente Medidas 4 x 6 metros 2 habitaciones 4 x 4 METROS Amplio espacio para parqueo para 4 a 6 vehículos A orilla de la calle QUE VA DESDE EL DEPARTAMENTO DE SANTA ANA HACÍA SAN SALVADOR a 10 minutos de centros comerciales a su alrededor SU VALOR ES DE $ 285.000 DÓLARES .",
    specs: {
      habitaciones: 7,
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "840 m² / 1,202 v²",
      parqueos: "6",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-volc",
    type: "propiedad",
    title: "Terreno Exclusivo en el volcan 1,713V²",
    price: 230000,
    location: "El Volcán",
    operacion: "Venta",
    summary: "TERRENO EXCLUSIVO EN VENTA – EL VOLCÁN Si buscas invertir en una zona privilegiada, esta es una excelente oportunidad. Ubicación…",
    description:
      "TERRENO EXCLUSIVO EN VENTA – EL VOLCÁN Si buscas invertir en una zona privilegiada, esta es una excelente oportunidad. Ubicación estratégica, cerca de reconocidos restaurantes y a orilla de calle, con fácil acceso y alta plusvalía. Área: 1,713 v² Precio: $230,000 Ideal para desarrollar una residencia de lujo, un proyecto turístico o una inversión con gran potencial.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,197.9 m² / 1,713 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-clau",
    type: "propiedad",
    title: "Terreno Blvd Claudia Lars",
    price: 135000,
    location: "Sacacoyo",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EXCELENTE UBICACION A LA PAR DE CLAUDIA LARS. A 2 MINUTOS DE DESVIO A SACACOYO CON ACCESO CALLE A SONSONATE, SANTA ANA,…",
    description:
      "SE VENDE TERRENO EXCELENTE UBICACION A LA PAR DE CLAUDIA LARS. A 2 MINUTOS DE DESVIO A SACACOYO CON ACCESO CALLE A SONSONATE, SANTA ANA, SAN SAVADOR. IDEAL PARA PROYECTO CABAÑA, PREDIO FURGONES, RESTAURANT Y OTROS. ACCESO EN CUALQUIER VEHÍCULO CALLE DE INGRESO PLANA MEDIDA ES DE 2,300M² TERRENO TOTALMENTE PLANO ACCESO EN CUALQUIER VEHÍCULO. CON FACTIBILIDAD DE LUZ Y AGUA. TIERRA TOTALMENTE FERTIL. SE LLEGA SIN DIFICULTAD. SU VALOR ES DE $ 135.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,300 m² / 3,291 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-ilop",
    type: "propiedad",
    title: "2Mns Lago de Ilopango",
    price: 1100000,
    location: "Ilopango",
    operacion: "Venta",
    summary: "SE VENDEN 2 MANZANAS DE TIERRA EQUIVALENTE A 20.000 VARAS² EN TOTAL EN EL LAGO DE ILOPANGO CON VISTA ESPECTACULAR IDEAL PARA HOTELES Y…",
    description:
      "SE VENDEN 2 MANZANAS DE TIERRA EQUIVALENTE A 20.000 VARAS² EN TOTAL EN EL LAGO DE ILOPANGO CON VISTA ESPECTACULAR IDEAL PARA HOTELES Y DESAROLLO INMOBILIARIO A 500 METROS DEL TURICENTRO APULO EN DIRECCION AL CLUB SALVADOREÑO / UBICACIÓN PRIVILEGIADA CANTON APANCINO.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "13,974 m² / 20,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-flor",
    type: "propiedad",
    title: "Terreno Canton flor amarilla",
    price: 135000,
    location: "Flor Amarilla",
    operacion: "Venta",
    summary: "SE VENDE TERRENO CON VISTA ESPECTACULAR AL LAGO DE COATEPEQUE DE 2500 VARAS² EN CANTON FLOR AMARILLA SEMIPLANO CALLE EN DIRECCION A LOS…",
    description:
      "SE VENDE TERRENO CON VISTA ESPECTACULAR AL LAGO DE COATEPEQUE DE 2500 VARAS² EN CANTON FLOR AMARILLA SEMIPLANO CALLE EN DIRECCION A LOS RESTAURANTES SUPER BIEN UBICADO ACCESO EN CUALQUIER VEHÍCULO CALLE DE TIERRA PLANO PLANO CON 26 METROS DE ANCHO POR 75 METROS DE LARGO / SE LLEGA SIN DIFICULTAD.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,747.5 m² / 2,500 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-huiz",
    type: "propiedad",
    title: "6Mnz Huizucar",
    price: 900000,
    location: "Huizúcar",
    operacion: "Venta",
    summary: "SE VENDE 6 MANZANAS DE TERRENO. EN HUIZUCAR LA LIBERTAD. CON VISTA ESPECTACULAR COMPLEJO PRIVADO RESIDENCIAL EL ENCANTO GOLF COUNTRY CLUB .…",
    description:
      "SE VENDE 6 MANZANAS DE TERRENO. EN HUIZUCAR LA LIBERTAD. CON VISTA ESPECTACULAR COMPLEJO PRIVADO RESIDENCIAL EL ENCANTO GOLF COUNTRY CLUB . TOPOGRAFÍA IRREGULAR . CON FACTIBILIDAD DE AGUA POTABLE Y LUZ ELÉCTRICA. ACCESO EN CUALQUIER VEHÍCULO A 20 MINUTOS DE LA CARRETERA AL PUERTO DE LA LIBERTAD IDEAL PARA PROYECTO INMOBILIARIO, APARTAMENTOS RB&B O PROYECTO AGRÍCOLA Y SIEMPRE EN UNA ZONA ACCESIBLE DE ALTA PLUS VALIA SU VALOR ES DE $900.000 DÓLARES. SU VALOR POR VARA ES DE $ 15 USDS LA VARA² ES UN SUPER PRECIO .",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "41,922 m² / 60,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-ahua",
    type: "propiedad",
    title: "20 Mnz en Ahuachapán",
    price: 175000,
    location: "Ahuachapán",
    operacion: "Venta",
    summary: "SE VENDE PROPIEDAD COMPLETA 20 MANZANAS EN AHUACHAPAN TOPOGRAFIA PLANAS Y SEMIPLANA SE NECESITA VEHICULO 4X4 PARA ACCESAR A LA PROPIEDAD .…",
    description:
      "SE VENDE PROPIEDAD COMPLETA 20 MANZANAS EN AHUACHAPAN TOPOGRAFIA PLANAS Y SEMIPLANA SE NECESITA VEHICULO 4X4 PARA ACCESAR A LA PROPIEDAD . SE PUEDE HACER USO DE PANELES SOLARES. Y AGUA SOLO PERFORANDO PARA POZO ARTESANAL . SE SITÚA A 8 MINUTOS DE LA CARRETERA QUE CONDUCE DESDE AHUACHAPAN A TACUBA Y 15 MINUTOS DEL CENTRO DE AHUACHAPAN. SU VALOR ES DE $175.000 DÓLARES . UN SUPER PRECIO !",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "139,740 m² / 200,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-lagu",
    type: "propiedad",
    title: "Terreno 18,000V² - Cantón planes de la laguna",
    price: 92000,
    location: "Planes de la Laguna",
    operacion: "Venta",
    summary: "SE VENDE TERRENO DE 18.000 VARAS² EN SANTA ANA CON VISTA AL LAGO DE COATEPEQUE. SE SITÚA EN EL CANTÓN PLANES DE LA LAGUNA / ACCESO EN…",
    description:
      "SE VENDE TERRENO DE 18.000 VARAS² EN SANTA ANA CON VISTA AL LAGO DE COATEPEQUE. SE SITÚA EN EL CANTÓN PLANES DE LA LAGUNA / ACCESO EN CUALQUIER VEHÍCULO CALLE DE TIERRA FACTIBILIDAD DE AGUA A 100 METROS DE DISTANCIA / LUZ SOLO CON PANELES SOLARES TOPOGRAFIA SEMIPLANA SU VALOR ES DE $ 92.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "12,582 m² / 18,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-atac",
    type: "propiedad",
    title: "1.7Mnz - Ataco",
    price: 935000,
    location: "Ataco",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EN ATACO 1.7 MANZANA EQUIVALENTE A 17.000 VARAS² CERCA DEL PUEBLO Y CERCA DE TODA LA URBANIZACIÓN. FACTIBILIDAD DE LUZ…",
    description:
      "SE VENDE TERRENO EN ATACO 1.7 MANZANA EQUIVALENTE A 17.000 VARAS² CERCA DEL PUEBLO Y CERCA DE TODA LA URBANIZACIÓN. FACTIBILIDAD DE LUZ ELECTRICA Y AGUA POTABLE CON 100 METROS DE FRENTE A 3 MINUTOS DE LA CIUDAD DE ATACO . TOPOGRAFIA 100% PLANA . ACCESO EN CUALQUIER VEHÍCULO SU VALOR ES DE $55 DOLARES LA VARA² UN TOTAL DE $ 935.000 DOLARES SE PUEDE NEGOCIAR UN POCO TODAVÍA.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "11,877 m² / 17,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-card",
    type: "propiedad",
    title: "Terreno Santa Ana - Cardedeu",
    price: 130000,
    location: "Cardedeu",
    operacion: "Venta",
    summary: "SE VENDE TERRENO EN SANTA ANA CON VISTA AL LAGO DE COATEPEQUE A 200 METROS DEL LAGO . 4000 VARAS² CUENTA CON AGUA POTABLE Y FACTIBILIDAD DE…",
    description:
      "SE VENDE TERRENO EN SANTA ANA CON VISTA AL LAGO DE COATEPEQUE A 200 METROS DEL LAGO . 4000 VARAS² CUENTA CON AGUA POTABLE Y FACTIBILIDAD DE LUZ ELECTRICA . CUENTA CON ARBOLES FRUTALES COMO CAFE , MANGO , JOCOTE , GUINEO , CACAO , ACHOTE Y FLOR DE ISOTE . TAMBIEN SE SITÚA CERCA DE CARDEDEU RESIDENT Y DEMAS RESTAURANTES TOPOGRAFIA PLANA Y SEMIPLANA 50/50 ACCESO EN CUALQUIER VEHÍCULO SU VALOR ES DE $ 130.000 DÓLARES.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,796 m² / 4,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-juju",
    type: "propiedad",
    title: "335Mnz en Jujutla",
    price: 2847500,
    location: "Jujutla",
    operacion: "Venta",
    summary: "Se propiedad privilegiada de 335 manzanas en Jujutla. - Ubicada en Ahuachapán Sur; conformada por 3 fincas: El Escondido, Copinula y Casa…",
    description:
      "Se propiedad privilegiada de 335 manzanas en Jujutla. - Ubicada en Ahuachapán Sur; conformada por 3 fincas: El Escondido, Copinula y Casa de j Sin. - La propiedad tiene aproximadamente 2 kilómetros sobre la carretera. - 100 manzanas cultivadas de café (seccionadas en 40 y 60). - Riqueza hídrica unica: cuenta con 3 ríos que pasan por la propiedad y 6 espectaculares cascadas. - 16 minas de piedra laja; 5 minas están ubicadas directamente sobre la carretera. - Acceso total a servicios de agua potable y luz eléctrica. - Acceso fácil para cualquier tipo de vehículo. - Valor por manzana: $8,500 dólares. - UN SUPER PRECIO !",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,340,645 m² / 3,350,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-mora",
    type: "propiedad",
    title: "4Mnz en Morazán",
    price: 140000,
    location: "Morazán",
    operacion: "Venta",
    summary: "SE VENDEN 4 MANZANAS EN EL DEPARTAMENTO DE MORAZÁN A 25 MINUTOS DE LA CARRETERA PRINCIPAL EN DIRECCION A SAN FRANCISCO GOTERA IDEAL PARA…",
    description:
      "SE VENDEN 4 MANZANAS EN EL DEPARTAMENTO DE MORAZÁN A 25 MINUTOS DE LA CARRETERA PRINCIPAL EN DIRECCION A SAN FRANCISCO GOTERA IDEAL PARA GANADERÍA CASERÍO SANTA MARTÁ TOPOGRAFÍA SEMIPLANA QUEBRADA EN INVIERNO LA FACTIBILIDAD DE LUZ ELECTRICA Y AGUA POTABLE SE ENCUENTRA A 200 METROS DE DISTANCIA SU CALOR ES DE $140.000 PERSONAS INTERESADAS EN COMPRAR Y AGENDAR UNA VISITA FAVOR CONTACTARCE",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "27,948 m² / 40,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-atac2",
    type: "propiedad",
    title: "Finca 10Mnz - Ataco Ahuachapan",
    price: 750000,
    location: "Ataco",
    operacion: "Venta",
    summary: "SE VENDE FINCA DE 10 MANZANAS EN ATACO",
    description:
      "SE VENDE FINCA DE 10 MANZANAS EN ATACO AHUACHAPAN.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "69,870 m² / 100,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-cost",
    type: "propiedad",
    title: "Rancho a remodelar - Costa Azul, Sonsonate",
    price: 180000,
    location: "Costa Azul",
    operacion: "Venta",
    summary: "SE VENDE RANCHO A REMODELAR PLAYA COSTA AZUL, SONSONATE. A 300 MTS DEL MAR. (NO FRENTE AL MAR) IDEAL PARA DESCANSAR CON AMIGOS Y FAMILIA…",
    description:
      "SE VENDE RANCHO A REMODELAR PLAYA COSTA AZUL, SONSONATE. A 300 MTS DEL MAR. (NO FRENTE AL MAR) IDEAL PARA DESCANSAR CON AMIGOS Y FAMILIA MEDIDAS 600 M² AMPLIA PISCINA (SIN FILTRO) DOS HABITACIONES COREEDOR AMPLIO BAÑO, DUCHA. AREA DE LAVADO AGUA DE POZO Y PUNTA. CON ENERGIA ELECTRICA ACTIVA. AMPLIO PARQUEO. FACIL ACCESO. A 5 MINUTOS DE CARRETERA. CALLE DE TIERRA Y PLANA. A 5 MINUTOS DE LA PLAYA.",
    specs: {
      habitaciones: 2,
      banos: 1,
      areaConstruccion: "—",
      areaTerreno: "600 m² / 858 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-delg",
    type: "propiedad",
    title: "Propiedad en Ciudad Delgado",
    price: 420000,
    location: "Ciudad Delgado",
    operacion: "Venta",
    summary: "SE VENDE INMUEBLE UBICACIÓN PRIVILEGIADA ZONA COMERCIAL EN SAN SALVADOR CIUDAD DELGADO MUY BIEN UBICADO SUS MEDIDAS SON 10 METROS DE FRENTE…",
    description:
      "SE VENDE INMUEBLE UBICACIÓN PRIVILEGIADA ZONA COMERCIAL EN SAN SALVADOR CIUDAD DELGADO MUY BIEN UBICADO SUS MEDIDAS SON 10 METROS DE FRENTE POR 25 METROS DE FONDO CUENTA CON 8 HABITACIONES Y 3 BAÑOS / SE SITUA A POCOS METROS DE AVENIDA JUAN BERTIS CIUDAD DELGADO UNA CALLE MUY TRANSITADA Y A 150 METROS DE LOS JUZGADOS DE CIUDAD DELGADO EN DIRECCION HACIA LA PLACITA DELGADO IDEAL PARA TALLER , BODEGAS , Y TODO TIPO DE NEGOCIO SU VALOR ES DE $ 420.000 DÓLARES .",
    specs: {
      habitaciones: 8,
      banos: 3,
      areaConstruccion: "—",
      areaTerreno: "250 m² / 357 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-acaj",
    type: "propiedad",
    title: "83Mnz Sonsonate - Acajutla",
    price: 2241000,
    location: "Acajutla",
    operacion: "Venta",
    summary: "SE VENDEN 83 MANZANAS 100% PLANAS / CON CULTIVO DE CAÑA CON SU PROPIO SISTEMA DE RIEGO / LUZ ELECTRICA AGUA POTABLE / 2 GALERAS GRANDES…",
    description:
      "SE VENDEN 83 MANZANAS 100% PLANAS / CON CULTIVO DE CAÑA CON SU PROPIO SISTEMA DE RIEGO / LUZ ELECTRICA AGUA POTABLE / 2 GALERAS GRANDES PARA GUARDAR TRACTORES Y TODA LA MAQUINARIA Ubicacion: Sonsonate. Acajutla. Cerca de Gasolinera kilo 5. A unos 8 minutos de la carretera principal. Dos casas de seguridad SU VALOR TOTAL ES DE $2.241.000 MILLONES QUE EQUIVALEN A $27.000 DÓLARES POR MANZANA LA VENTA ES TOTAL TOTAL Y TAMBIEN SE PUEDEN VENDER MINIMO 30 MANZANAS COMO MINIMO UBICACION PRIVILEGIADA !",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "579,921 m² / 830,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-jaya",
    type: "propiedad",
    title: "Finca de Café en venta - Jayaque",
    price: 298000,
    location: "Jayaque",
    operacion: "Venta",
    summary: "SE VENDE FINCA DE CAFÉ EN JAYAQUE CON ACCESO A ORILLA DE CALLE - IDEAL TAMBIEN PARA PROYECTO URBANO - ACCESO EN CALLE PAVIMENTADA - CUENTA…",
    description:
      "SE VENDE FINCA DE CAFÉ EN JAYAQUE CON ACCESO A ORILLA DE CALLE - IDEAL TAMBIEN PARA PROYECTO URBANO - ACCESO EN CALLE PAVIMENTADA - CUENTA CON LUZ ELECTRICA Y AGUA POTABLE CON VISTA ESPECTACULAR A LA CIUDAD. 39.000 VARAS² EQUIVALENTES A 27.000 METROS² TAMBIEN CONSTA DE UNA CABAÑA GRANDE DE 2 NIVELES - DE MADERA , 2 BAÑOS COMPLETOS - CISTERNA DE 40 BARRILES - PISO DE LAJA , UNA GLORIETA , SALA DE ESTAR - SALA DE ESTUDIO - CUENTA CON 2 PORTONES DE ACCESO BODEGA Y CASITA PARA LOS ENCARGADOS.",
    specs: {
      habitaciones: "—",
      banos: 2,
      areaConstruccion: "—",
      areaTerreno: "27,000 m² / 39,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-coat",
    type: "propiedad",
    title: "2Mnz - Coatepeque",
    price: 365000,
    location: "Coatepeque",
    operacion: "Venta",
    summary: "SE VENDEN 2 MANZANAS ACCESO A 200 METROS A ORILLA DE CALLE . EN DIRECCION AL CERRO VERDE ! CERCA DEL MIRADOR TURISTICO ! EL ANTEOJO DE…",
    description:
      "SE VENDEN 2 MANZANAS ACCESO A 200 METROS A ORILLA DE CALLE . EN DIRECCION AL CERRO VERDE ! CERCA DEL MIRADOR TURISTICO ! EL ANTEOJO DE COATEPEQUE ! TIENEN ACCESO INMEDIATO DESDE LA CALLE HACIA EL CERRO VERDE A 200 METROS ESTAN LA PROPIEDAD Y TIENEN UNA VISTA ESPECTACULAR AL LAGO DE COATEPEQUE ! PROPIEDAD PERFECTA PARA HACER TORRE DE APARTAMENTOS, CENTRO COMERCIAL, PROYECTO HABITACIONAL , HOTELES, RESTAURANTES , CABAÑAS ... ENTRE OTROS RUBROS DONDE SE EXPLOTÉ LA UBICACIÓN QUE TIENE.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "13,974 m² / 20,000 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-copa-3",
    type: "propiedad",
    title: "Lote 3 - Copapayo",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "LOTE EN VENTA – COPAPAYO. Tranquilidad y accesibilidad en un solo lugar. Perfecto para vivir o invertir. Área: 842.5 m² / 1,205.47 vrs².…",
    description:
      "LOTE EN VENTA – COPAPAYO. Tranquilidad y accesibilidad en un solo lugar. Perfecto para vivir o invertir. Área: 842.5 m² / 1,205.47 vrs². Acceso por servidumbre. Energía eléctrica disponible. Agua potable. Entorno natural, cerca del río. Precio: $29,000",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },
  {
    id: "prop-copa-1",
    type: "propiedad",
    title: "Lote 1 - Copapayo",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "LOTE EN VENTA – COPAPAYO. A pocos minutos de la carretera principal. Excelente opción para construir o invertir. Área: 842.5 m² / 1,205.47…",
    description:
      "LOTE EN VENTA – COPAPAYO. A pocos minutos de la carretera principal. Excelente opción para construir o invertir. Área: 842.5 m² / 1,205.47 vrs². Acceso por servidumbre privada. Energía eléctrica disponible. Agua potable. Zona tranquila y fresca. Precio: $29,000",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: [],
    images: ["images/site/placeholder-propiedad.svg"],
  },

  // ---------------- VEHÍCULOS ----------------
  {
    id: "veh-rzr4pro",
    type: "vehiculo",
    title: "Polaris RZR 4 PRO (Buggy/UTV)",
    price: 29500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE UTV MARCA POLARIS. ES EL RZR TURBO MOTOR 1000 CON APENAS 2000 MILLAS IMPORTADA UNA EXPERIENCIA SIN IGUAL CON TIJERAS Y ESTRIBOS…",
    description:
      "SE VENDE UTV MARCA POLARIS. ES EL RZR TURBO MOTOR 1000 CON APENAS 2000 MILLAS IMPORTADA UNA EXPERIENCIA SIN IGUAL CON TIJERAS Y ESTRIBOS SUPER ATB , SUSPENSIÓN FOX IMPECABLE SU VALOR ES DE $29.500 DÓLARES NO SE ACEPTAN CAMBIOS. SE MUESTRA ÚNICAMENTE EN UNA DE NUESTRAS OFICINAS EN SANTA TECLA",
    specs: {
      anio: "—",
      kilometraje: "3,218 km",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-cfmo2020",
    type: "vehiculo",
    title: "Cuadrimoto CF Moto 2020",
    price: 8500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "Cuadrimoto CF Moto 2020 disponible. Contáctanos por WhatsApp para más detalles y coordinar una prueba de",
    description:
      "Cuadrimoto CF Moto 2020 disponible. Contáctanos por WhatsApp para más detalles y coordinar una prueba de manejo.",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-f1502022",
    type: "vehiculo",
    title: "Ford F150 2022",
    price: 38000,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE FORD F150 2022 4X4 EN EXCELENTE",
    description:
      "SE VENDE FORD F150 2022 4X4 EN EXCELENTE ESTADO",
    specs: {
      anio: 2022,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-acco2020",
    type: "vehiculo",
    title: "Honda Accord 2020",
    price: 19900,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE HONDA ACCORD 2020 EN EXCELENTE ESTADO SU VALOR ES DE $19.900",
    description:
      "SE VENDE HONDA ACCORD 2020 EN EXCELENTE ESTADO SU VALOR ES DE $19.900 DÓLARES",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-q3sl2018",
    type: "vehiculo",
    title: "Audi Q3 S Line 2018",
    price: 16500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE AUDI Q3 S LINE 2018 IMPORTADA CON TODAS LAS BOLSAS DE AIRE BUENAS QUATRO ( 4X4 ) MOTOR 2.0 TURBO GASOLINA DE 4 CILINDROS TAPICERIA…",
    description:
      "SE VENDE AUDI Q3 S LINE 2018 IMPORTADA CON TODAS LAS BOLSAS DE AIRE BUENAS QUATRO ( 4X4 ) MOTOR 2.0 TURBO GASOLINA DE 4 CILINDROS TAPICERIA EN CUERO Y TECHO PANORAMICO 75.000 MILLAS RECORRIDAS A TODA REVISION MECANICA PROFESIONAL . ENCENDIDO DE BOTON CON LLAVE DE PROXIMIDAD - FRENO DE MANO ELECTRONICO - BAUL ELECTRICO SUPER ECONOMICA SU VALOR ES DE $16.500 DOLARES NO CAMBIOS NO . SOLO VENTA DE CONTADO",
    specs: {
      anio: 2018,
      kilometraje: "120,700 km",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-mazd2016",
    type: "vehiculo",
    title: "Mazda 3 2016",
    price: 7900,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE MAZDA 3 2016 SU VALOR ES DE $7.900",
    description:
      "SE VENDE MAZDA 3 2016 SU VALOR ES DE $7.900 DÓLARES",
    specs: {
      anio: 2016,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Financiamiento disponible (prima desde $3,160)"],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-fron2021",
    type: "vehiculo",
    title: "Nissan Frontier King Cab 2021",
    price: 13500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE NISSAN FRONTIER 2021 KING CAB SU VALOR ES DE $13.500",
    description:
      "SE VENDE NISSAN FRONTIER 2021 KING CAB SU VALOR ES DE $13.500 DÓLARES",
    specs: {
      anio: 2021,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Financiamiento disponible (prima desde $5,400)"],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-outl2020",
    type: "vehiculo",
    title: "Mitsubishi Outlander 2020",
    price: 13500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE MITSUBISHI OUTLANDER 2020 SU VALOR ES DE $13.500",
    description:
      "SE VENDE MITSUBISHI OUTLANDER 2020 SU VALOR ES DE $13.500 DÓLARES",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Financiamiento disponible (prima desde $5,500)"],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-kona2023",
    type: "vehiculo",
    title: "Hyundai Kona AWD (4X4) 2023",
    price: 15500,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE HYUNDAI KONA AWD (4X4) 2023 SU VALOR ES DE $15.500",
    description:
      "SE VENDE HYUNDAI KONA AWD (4X4) 2023 SU VALOR ES DE $15.500 DÓLARES",
    specs: {
      anio: 2023,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Financiamiento disponible (prima desde $6,200)"],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
  {
    id: "veh-l2002013",
    type: "vehiculo",
    title: "Mitsubishi L200 2013",
    price: 20000,
    location: "El Salvador",
    operacion: "Venta",
    summary: "SE VENDE MITSUBISHI L200 2013 SU VALOR ES DE $20.000",
    description:
      "SE VENDE MITSUBISHI L200 2013 SU VALOR ES DE $20.000 DÓLARES",
    specs: {
      anio: 2013,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: [],
    images: ["images/site/placeholder-vehiculo.svg"],
  },
];