/* ============================================
   PIMTEL — Datos del catálogo
   ------------------------------------------------
   Este es el ÚNICO archivo que hay que tocar para
   agregar, editar o quitar propiedades y vehículos.

   Cada ficha es un bloque { ... } dentro del arreglo
   `listings`. Copia un bloque existente, pégalo,
   cambia el "id" (debe ser único) y actualiza los
   demás datos.

   type: "propiedad" o "vehiculo"
   images: lista de rutas a fotos. Mientras no haya
   fotos reales, se usan las imágenes de marcador
   images/site/placeholder-propiedad.svg o
   images/site/placeholder-vehiculo.svg

   video (opcional): agrega esta línea a cualquier ficha
   para mostrar un video. Al pasar el mouse sobre la
   tarjeta (o mantener presionado en el celular) se
   reproduce una vista previa; en la ficha aparece un
   reproductor completo. Acepta dos formas:
     video: "https://www.youtube.com/watch?v=XXXXXXXXXXX"
     video: "images/listings/veh-001.mp4"
   Para videos largos (recorridos completos) se recomienda
   subirlos a YouTube como "no listado" y pegar el link acá,
   en vez de subir el archivo de video directo al repositorio.
   ============================================ */

const listings = [
  // ---------------- PROPIEDADES ----------------
  {
    id: "prop-copa-2",
    type: "propiedad",
    title: "Lote en Copapayo — Zona con plusvalía",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. En una zona con plusvalía y fácil acceso. Ideal para casa de descanso o proyecto…",
    description:
      "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. En una zona con plusvalía y fácil acceso. Ideal para casa de descanso o proyecto familiar. $29,000. Copapayo, El Salvador, cerca del río.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: ["842.5 m² (1,205 v²)", "Zona con plusvalía y fácil acceso", "Energía eléctrica disponible y agua potable", "Cerca del río, entorno natural", "Lote ya segregado; acceso por servidumbre privada en proyecto (plano), aún no construida"],
    images: ["images/listings/copa/02.jpg", "images/listings/copa/01.jpg", "images/listings/copa/03.jpg", "images/listings/copa/04.jpg", "images/listings/copa/05.jpg"],
    video: "images/listings/copa/video.mp4",
  },
  {
    id: "prop-lour1",
    type: "propiedad",
    title: "Casa nueva en Lourdes Colón — El Conacaste",
    price: 195000,
    location: "Colón",
    badges: ["Residencial privado"],
    operacion: "Venta",
    summary: "Casa nueva a estrenar en residencial privado exclusivo, Lourdes Colón, La Libertad. El Conacaste es una mini residencial de solo 20 casas…",
    description:
      "Casa nueva a estrenar en residencial privado exclusivo, Lourdes Colón, La Libertad. El Conacaste es una mini residencial de solo 20 casas en privado, con área verde común y máxima privacidad. Desde $195,000. Modelos Premium Plus con piscina privada hasta $250,000. Financiamiento con Banco Industrial: plazo hasta 30 años, tasa desde 7.40%, hasta 90% del valor financiado, cuota mensual desde $1,225. Se aceptan trámites bancarios y pago en efectivo. Lourdes Colón, La Libertad, El Salvador. Zona de alta plusvalía y crecimiento.",
    specs: {
      habitaciones: 3,
      banos: 2,
      areaConstruccion: "—",
      areaTerreno: "300 m² / 429 v²",
      parqueos: "2",
    },
    features: ["300 m² de terreno (12.5 × 24 m)", "3 habitaciones, habitación principal con walk-in closet", "2 baños completos", "Cuarto de servicio y lavandería", "Sala, comedor y cocina abierta equipada", "Amplio jardín privado", "Cochera para 2 vehículos", "Acabados premium: porcelanato, ventanales de piso a techo, closets de madera, instalación eléctrica con circuitos independientes"],
    images: ["images/listings/cona/01.jpg", "images/listings/cona/02.jpg", "images/listings/cona/03.jpg", "images/listings/cona/04.jpg", "images/listings/cona/05.jpg", "images/listings/cona/06.jpg", "images/listings/cona/07.jpg", "images/listings/cona/08.jpg", "images/listings/cona/09.jpg", "images/listings/cona/10.jpg", "images/listings/cona/11.jpg", "images/listings/cona/12.jpg", "images/listings/cona/13.jpg", "images/listings/cona/14.jpg", "images/listings/cona/15.jpg", "images/listings/cona/16.jpg", "images/listings/cona/17.jpg", "images/listings/cona/18.jpg", "images/listings/cona/19.jpg", "images/listings/cona/20.jpg", "images/listings/cona/21.jpg", "images/listings/cona/22.jpg", "images/listings/cona/23.jpg"],
  },
  {
    id: "prop-atac4",
    type: "propiedad",
    title: "Terreno a orilla de calle en Ataco",
    price: 185000,
    location: "Ataco",
    badges: ["Financiamiento sin interés"],
    operacion: "Venta",
    summary: "Terreno de 1,200 m² (1,717 v²) a orilla de calle en Ataco, sobre la Ruta de las Flores, a 30 metros del Restaurante La Pampa. Zona de alta…",
    description:
      "Terreno de 1,200 m² (1,717 v²) a orilla de calle en Ataco, sobre la Ruta de las Flores, a 30 metros del Restaurante La Pampa. Zona de alta demanda y plusvalía. $185,000 — precio fijo. Venta al contado o por banco. Opción de financiamiento: $100,000 de prima y el resto hasta en 30 meses sin intereses. Ataco, Ahuachapán, El Salvador — Ruta de las Flores, a 30 metros del Restaurante La Pampa.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,200 m² / 1,717 v²",
      parqueos: "—",
    },
    features: ["1,200 m² (1,717 v²)", "16 m de frente x 75 m de fondo", "Doble acceso (permite parqueo anexo en la parte trasera)", "Terreno plano", "Factibilidad de luz eléctrica y agua potable", "Ideal para negocio, restaurante o desarrollo vertical"],
    images: ["images/listings/atac4/01.jpg", "images/listings/atac4/02.jpg", "images/listings/atac4/03.jpg", "images/listings/atac4/04.jpg", "images/listings/atac4/05.jpg", "images/listings/atac4/06.jpg"],
  },
  {
    id: "prop-occi",
    type: "propiedad",
    title: "Mini condominio en Santa Ana — ya genera ingresos",
    price: 450000,
    location: "Santa Ana",
    badges: ["Ya genera ingresos"],
    operacion: "Venta",
    summary: "Mini condominio de 462 m² (661 v²) en Colonia San José, Santa Ana, sobre la carretera a Metapán. Una inversión inmobiliaria que genera…",
    description:
      "Mini condominio de 462 m² (661 v²) en Colonia San José, Santa Ana, sobre la carretera a Metapán. Una inversión inmobiliaria que genera $1,200 mensuales desde el primer día. Actualmente todas las habitaciones están alquiladas, generando $1,200 mensuales. Precio de venta: $450,000. Colonia San José, carretera a Metapán, antes de llegar a Santa Ana Norte.",
    specs: {
      habitaciones: 10,
      banos: 10,
      areaConstruccion: "—",
      areaTerreno: "462 m² / 661 v²",
      parqueos: "5",
    },
    features: ["462 m² (661 v²), 11 m de ancho x 42 m de largo", "10 habitaciones, cada una con baño completo", "Área de lavandería independiente", "Energía eléctrica y agua potable", "Parqueo en línea hasta para 5 vehículos", "Potencial de construir un segundo nivel para aumentar la renta"],
    images: ["images/listings/occi/01.jpg", "images/listings/occi/02.jpg", "images/listings/occi/03.jpg", "images/listings/occi/04.jpg", "images/listings/occi/05.jpg", "images/listings/occi/06.jpg", "images/listings/occi/07.jpg", "images/listings/occi/08.jpg", "images/listings/occi/09.jpg", "images/listings/occi/10.jpg", "images/listings/occi/11.jpg", "images/listings/occi/12.jpg", "images/listings/occi/13.jpg", "images/listings/occi/14.jpg"],
  },
  {
    id: "prop-atac3",
    type: "propiedad",
    title: "Finca de 17 manzanas en Ataco — Con casa patronal",
    price: 260000,
    location: "Ataco",
    badges: ["Requiere 4x4"],
    operacion: "Venta",
    summary: "Finca de 17 manzanas (170,000 v² / 118,779 m²) en Ataco, a 10 minutos del pueblo y a 1,200 metros sobre el nivel del mar. Clima fresco de…",
    description:
      "Finca de 17 manzanas (170,000 v² / 118,779 m²) en Ataco, a 10 minutos del pueblo y a 1,200 metros sobre el nivel del mar. Clima fresco de montaña y casa patronal incluida. $260,000. Ataco, Ahuachapán, El Salvador, a 10 minutos del pueblo.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "118,779 m² / 170,000 v²",
      parqueos: "—",
    },
    features: ["17 manzanas (170,000 v² / 118,779 m²)", "Casa patronal incluida", "Se divide en 3 ubicaciones en un radio de 300 a 500 metros", "1,200 metros sobre el nivel del mar", "Topografía plana y semiplana", "Acceso con vehículo 4x4"],
    images: ["images/listings/atac3/01.jpg", "images/listings/atac3/02.jpg", "images/listings/atac3/03.jpg", "images/listings/atac3/04.jpg", "images/listings/atac3/05.jpg", "images/listings/atac3/06.jpg", "images/listings/atac3/07.jpg", "images/listings/atac3/08.jpg", "images/listings/atac3/09.jpg"],
  },
  {
    id: "prop-cang",
    type: "propiedad",
    title: "Terreno cerca de la playa en Cangrejera — $38,000",
    price: 38000,
    location: "Cangrejera",
    operacion: "Venta",
    summary: "Terreno plano de 349 m² (499 v²) en Cangrejera, La Libertad, a solo 700 metros de la playa. El precio de entrada ideal para tu casa o…",
    description:
      "Terreno plano de 349 m² (499 v²) en Cangrejera, La Libertad, a solo 700 metros de la playa. El precio de entrada ideal para tu casa o rancho de playa. $38,000 fijos. Cangrejera, La Libertad, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "349 m² / 499 v²",
      parqueos: "—",
    },
    features: ["349 m² (499 v²)", "12.96 m de frente x 27 m de fondo", "A 700 metros de la playa", "Terreno plano", "Ideal para casa o rancho de playa"],
    images: ["images/listings/cang/01.jpg"],
    video: "images/listings/cang/video.mp4",
  },
  {
    id: "prop-copa2",
    type: "propiedad",
    title: "Terreno plano en Copapayo, Armenia — $62,000",
    price: 62000,
    location: "Armenia",
    operacion: "Venta",
    summary: "Terreno de 828 m² (1,185 v²) en Copapayo, Armenia, Sonsonate, totalmente plano y fértil, a solo 4 minutos de la carretera. Cuenta con 3…",
    description:
      "Terreno de 828 m² (1,185 v²) en Copapayo, Armenia, Sonsonate, totalmente plano y fértil, a solo 4 minutos de la carretera. Cuenta con 3 accesos de entrada. $62,000. Copapayo, Armenia, Sonsonate, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "828 m² / 1,185 v²",
      parqueos: "—",
    },
    features: ["828 m² (1,185 v²)", "18 m de frente x 46 m de fondo", "3 accesos de entrada (uno con acceso a Claudia Lars)", "Acceso en cualquier vehículo, calle de tierra plana", "Energía eléctrica y agua disponibles (solo de activar)", "Tierra totalmente fértil, terreno 100% plano"],
    images: ["images/listings/copa2/01.jpg", "images/listings/copa2/02.jpg"],
    video: "images/listings/copa2/video.mp4",
  },
  {
    id: "prop-bazz",
    type: "propiedad",
    title: "Terreno sobre el Boulevard Bazzini — $95,000",
    price: 95000,
    location: "Blvd. Bazzini",
    operacion: "Venta",
    summary: "Terreno de 2,500 m² (3,577 v²) sobre el Boulevard Bazzini, cerca del desvío Hacienda Tránsito. Vista espectacular, ideal para un proyecto…",
    description:
      "Terreno de 2,500 m² (3,577 v²) sobre el Boulevard Bazzini, cerca del desvío Hacienda Tránsito. Vista espectacular, ideal para un proyecto de cabañas o casa de campo. $95,000. Boulevard Bazzini, cerca del desvío Hacienda Tránsito, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,500 m² / 3,577 v²",
      parqueos: "—",
    },
    features: ["2,500 m² (3,577 v²), compuesto por 2 parcelas", "Vista espectacular", "A 1 minuto de la carretera Bazzini y 4 minutos del desvío a Talnique, Jayaque y Ateos", "A 10 minutos de escuelas, centros comerciales y negocios de Lourdes", "Terreno semiplano, tierra fértil, calle de ingreso plana", "Ideal para cabañas, casa de campo o lugar de retiro"],
    images: ["images/listings/bazz/01.jpg", "images/listings/bazz/02.jpg", "images/listings/bazz/03.jpg", "images/listings/bazz/04.jpg", "images/listings/bazz/05.jpg", "images/listings/bazz/06.jpg"],
    video: "images/listings/bazz/video.mp4",
  },
  {
    id: "prop-copa-p",
    type: "propiedad",
    title: "Lote premium en Copapayo — Con pozo propio",
    price: 32000,
    location: "Copapayo",
    badges: ["Con pozo propio"],
    operacion: "Venta",
    summary: "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. El de mejor ubicación del proyecto: con pozo propio y doble acceso, en un entorno…",
    description:
      "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. El de mejor ubicación del proyecto: con pozo propio y doble acceso, en un entorno natural y tranquilo. $32,000. Copapayo, El Salvador, cerca del río.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: ["842.5 m² (1,205 v²)", "Pozo propio incluido y agua potable", "Energía eléctrica disponible", "Acceso por ambos extremos (colinda en su lado más largo con la servidumbre)", "Entorno natural, cerca del río", "Lote ya segregado; la calle de servidumbre interna está en proyecto (plano), aún no construida"],
    images: ["images/listings/copa/02.jpg", "images/listings/copa/01.jpg", "images/listings/copa/03.jpg", "images/listings/copa/04.jpg", "images/listings/copa/05.jpg"],
    video: "images/listings/copa/video.mp4",
  },
  {
    id: "prop-ssal2",
    type: "propiedad",
    title: "Terreno urbano de 598 m² en San Salvador — $198,000",
    price: 198000,
    location: "San Salvador",
    operacion: "Venta",
    summary: "Terreno urbano de 598 m² (856 v²) en San Salvador, con doble acceso y servicios cerca. Excelente ubicación para construir en la capital.…",
    description:
      "Terreno urbano de 598 m² (856 v²) en San Salvador, con doble acceso y servicios cerca. Excelente ubicación para construir en la capital. $198,000. San Salvador, El Salvador. Ingreso por el ex Restaurante La Herradura y por la 75 Avenida Norte.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "598 m² / 856 v²",
      parqueos: "—",
    },
    features: ["598 m² (856 v²)", "Doble acceso: por el ex Restaurante La Herradura y por la 75 Avenida Norte", "Servicio de agua potable", "Postes de alumbrado eléctrico"],
    images: ["images/listings/ssal2/01.jpg", "images/listings/ssal2/02.jpg", "images/listings/ssal2/03.jpg", "images/listings/ssal2/04.jpg", "images/listings/ssal2/05.jpg", "images/listings/ssal2/06.jpg", "images/listings/ssal2/07.jpg", "images/listings/ssal2/08.jpg", "images/listings/ssal2/09.jpg", "images/listings/ssal2/10.jpg", "images/listings/ssal2/11.jpg", "images/listings/ssal2/12.jpg", "images/listings/ssal2/13.jpg", "images/listings/ssal2/14.jpg", "images/listings/ssal2/15.jpg", "images/listings/ssal2/16.jpg"],
  },
  {
    id: "prop-ahua2",
    type: "propiedad",
    title: "Casa de lujo en Ahuachapán, Parque Concordia",
    price: 560000,
    location: "Ahuachapán",
    badges: ["Con piscina"],
    operacion: "Venta",
    summary: "Amplia residencia de lujo en Ahuachapán, a pocos metros del Parque Concordia. Una propiedad señorial con piscina y espacios generosos para…",
    description:
      "Amplia residencia de lujo en Ahuachapán, a pocos metros del Parque Concordia. Una propiedad señorial con piscina y espacios generosos para toda la familia, en una ubicación privilegiada. Precio: $560,000. Se aceptan trámites bancarios y pago de contado. Ahuachapán, a pocos metros del Parque Concordia, El Salvador. Zona céntrica de alta plusvalía.",
    specs: {
      habitaciones: 6,
      banos: 6,
      areaConstruccion: "—",
      areaTerreno: "—",
      parqueos: "2",
    },
    features: ["6 amplias habitaciones", "6 baños", "Piscina, deck y terraza", "2 salas de estar y sala comedor", "Cocina con desayunador", "Amplio jardín", "Espacio para 2 vehículos"],
    images: ["images/listings/ahua2/01.jpg", "images/listings/ahua2/02.jpg", "images/listings/ahua2/03.jpg", "images/listings/ahua2/04.jpg", "images/listings/ahua2/05.jpg", "images/listings/ahua2/06.jpg", "images/listings/ahua2/07.jpg", "images/listings/ahua2/08.jpg", "images/listings/ahua2/09.jpg", "images/listings/ahua2/10.jpg", "images/listings/ahua2/11.jpg", "images/listings/ahua2/12.jpg"],
    video: "images/listings/ahua2/video.mp4",
  },
  {
    id: "prop-cumb",
    type: "propiedad",
    title: "Terreno urbano en Cumbres de la Escalón",
    price: 1449250,
    location: "Cumbres de la Escalón",
    badges: ["Bajo el valor de mercado"],
    operacion: "Venta",
    summary: "Terreno urbano de 1,842.16 m² (2,635 v²) en Cumbres de la Escalón, San Salvador, la zona de mayor exclusividad y plusvalía del país. Listo…",
    description:
      "Terreno urbano de 1,842.16 m² (2,635 v²) en Cumbres de la Escalón, San Salvador, la zona de mayor exclusividad y plusvalía del país. Listo para construir. $1,449,250 ($550 por vara²). Cumbres de la Escalón, San Salvador, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,842.16 m² / 2,635 v²",
      parqueos: "—",
    },
    features: ["1,842.16 m² (2,635 v²)", "Topografía plana", "Listo para construir: casa grande o torre de apartamentos (desarrollo vertical)", "Factibilidad de luz eléctrica y agua potable", "Valor de $550 por vara², por debajo del valor de mercado actual"],
    images: ["images/listings/cumb/01.jpg", "images/listings/cumb/02.jpg", "images/listings/cumb/03.jpg", "images/listings/cumb/04.jpg", "images/listings/cumb/05.jpg", "images/listings/cumb/06.jpg", "images/listings/cumb/07.jpg", "images/listings/cumb/08.jpg", "images/listings/cumb/09.jpg"],
    video: "images/listings/cumb/video.mp4",
  },
  {
    id: "prop-sanv",
    type: "propiedad",
    title: "215 manzanas en San Vicente, Río Frío",
    price: 1720000,
    location: "San Vicente",
    operacion: "Venta",
    summary: "Gran propiedad de 215 manzanas en Cantón Río Frío, San Vicente, a 200 metros de la carretera principal. Doble potencial: producción…",
    description:
      "Gran propiedad de 215 manzanas en Cantón Río Frío, San Vicente, a 200 metros de la carretera principal. Doble potencial: producción agropecuaria y extracción de minerales. $8,000 por manzana — total $1,720,000. Venta total en un solo pago. Cantón Río Frío, San Vicente, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,502,205 m² / 2,150,000 v²",
      parqueos: "—",
    },
    features: ["215 manzanas (2,150,000 v²)", "2 ríos dentro de la propiedad", "Extracción de piedra, laja y otros minerales", "Ideal para ganadería y cultivo", "Topografía semiplana, acceso en cualquier vehículo", "Factibilidad de agua y luz eléctrica"],
    images: ["images/listings/sanv/01.jpg", "images/listings/sanv/02.jpg", "images/listings/sanv/03.jpg", "images/listings/sanv/04.jpg", "images/listings/sanv/05.jpg", "images/listings/sanv/06.jpg", "images/listings/sanv/07.jpg", "images/listings/sanv/08.jpg", "images/listings/sanv/09.jpg", "images/listings/sanv/10.jpg", "images/listings/sanv/11.jpg", "images/listings/sanv/12.jpg", "images/listings/sanv/13.jpg", "images/listings/sanv/14.jpg"],
  },
  {
    id: "prop-ssal",
    type: "propiedad",
    title: "Propiedad en San Salvador — A orilla de calle",
    price: 285000,
    location: "San Salvador",
    badges: ["Ya genera ingresos"],
    operacion: "Venta",
    summary: "Propiedad de 840 m² (1,202 v²) en San Salvador, a orilla de la calle que va de Santa Ana hacia San Salvador. Ya genera ingresos mensuales;…",
    description:
      "Propiedad de 840 m² (1,202 v²) en San Salvador, a orilla de la calle que va de Santa Ana hacia San Salvador. Ya genera ingresos mensuales; ideal para inversionistas. $285,000. San Salvador, El Salvador, a orilla de la calle que conecta Santa Ana con San Salvador.",
    specs: {
      habitaciones: 7,
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "840 m² / 1,202 v²",
      parqueos: "6",
    },
    features: ["840 m² (1,202 v²)", "7 habitaciones (5 de 4x6 m actualmente alquiladas + 2 de 4x4 m)", "Amplio parqueo para 4 a 6 vehículos", "Ubicación de alto tránsito, a 10 minutos de centros comerciales", "Genera ingresos mensuales"],
    images: ["images/listings/ssal/01.jpg", "images/listings/ssal/02.jpg", "images/listings/ssal/03.jpg", "images/listings/ssal/04.jpg", "images/listings/ssal/05.jpg", "images/listings/ssal/06.jpg", "images/listings/ssal/07.jpg", "images/listings/ssal/08.jpg", "images/listings/ssal/09.jpg", "images/listings/ssal/10.jpg", "images/listings/ssal/11.jpg", "images/listings/ssal/12.jpg", "images/listings/ssal/13.jpg", "images/listings/ssal/14.jpg", "images/listings/ssal/15.jpg", "images/listings/ssal/16.jpg", "images/listings/ssal/17.jpg", "images/listings/ssal/18.jpg", "images/listings/ssal/19.jpg", "images/listings/ssal/20.jpg", "images/listings/ssal/21.jpg", "images/listings/ssal/22.jpg", "images/listings/ssal/23.jpg", "images/listings/ssal/24.jpg", "images/listings/ssal/25.jpg", "images/listings/ssal/26.jpg", "images/listings/ssal/27.jpg", "images/listings/ssal/28.jpg", "images/listings/ssal/29.jpg", "images/listings/ssal/30.jpg", "images/listings/ssal/31.jpg", "images/listings/ssal/32.jpg", "images/listings/ssal/33.jpg", "images/listings/ssal/34.jpg"],
  },
  {
    id: "prop-volc",
    type: "propiedad",
    title: "Terreno exclusivo en El Volcán — A orilla de calle",
    price: 230000,
    location: "El Volcán",
    operacion: "Venta",
    summary: "Terreno de 1,197.9 m² (1,713 v²) en El Volcán, a orilla de calle y cerca de reconocidos restaurantes. Zona fresca de alta plusvalía.…",
    description:
      "Terreno de 1,197.9 m² (1,713 v²) en El Volcán, a orilla de calle y cerca de reconocidos restaurantes. Zona fresca de alta plusvalía. $230,000. El Volcán, San Salvador, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,197.9 m² / 1,713 v²",
      parqueos: "—",
    },
    features: ["1,197.9 m² (1,713 v²)", "A orilla de calle, con fácil acceso", "Cerca de restaurantes reconocidos", "Zona fresca de alta plusvalía", "Ideal para residencia de lujo o proyecto turístico"],
    images: ["images/listings/volc/01.jpg", "images/listings/volc/02.jpg", "images/listings/volc/03.jpg", "images/listings/volc/04.jpg", "images/listings/volc/05.jpg", "images/listings/volc/06.jpg", "images/listings/volc/07.jpg"],
  },
  {
    id: "prop-clau",
    type: "propiedad",
    title: "Terreno sobre el Boulevard Claudia Lars — $135,000",
    price: 135000,
    location: "Sacacoyo",
    operacion: "Venta",
    summary: "Terreno de 2,300 m² (3,291 v²) a un costado del Boulevard Claudia Lars, a 2 minutos del desvío a Sacacoyo. Plano y estratégico, con acceso…",
    description:
      "Terreno de 2,300 m² (3,291 v²) a un costado del Boulevard Claudia Lars, a 2 minutos del desvío a Sacacoyo. Plano y estratégico, con acceso a Sonsonate, Santa Ana y San Salvador. $135,000. A la par del Boulevard Claudia Lars, a 2 minutos del desvío a Sacacoyo, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,300 m² / 3,291 v²",
      parqueos: "—",
    },
    features: ["2,300 m² (3,291 v²)", "Acceso a Sonsonate, Santa Ana y San Salvador", "Acceso en cualquier vehículo, calle de ingreso plana", "Factibilidad de luz y agua", "Tierra totalmente fértil, terreno plano", "Ideal para cabaña, predio de furgones, restaurante y otros negocios"],
    images: ["images/listings/clau/01.jpg", "images/listings/clau/02.jpg", "images/listings/clau/03.jpg", "images/listings/clau/04.jpg", "images/listings/clau/05.jpg", "images/listings/clau/06.jpg", "images/listings/clau/07.jpg", "images/listings/clau/08.jpg"],
    video: "images/listings/clau/video.mp4",
  },
  {
    id: "prop-ilop",
    type: "propiedad",
    title: "2 manzanas frente al Lago de Ilopango",
    price: 1100000,
    location: "Ilopango",
    badges: ["Vista al lago"],
    operacion: "Venta",
    summary: "Terreno de 2 manzanas con vista espectacular al Lago de Ilopango, en Cantón Apancino, a 500 metros del Turicentro Apulo. Ubicación…",
    description:
      "Terreno de 2 manzanas con vista espectacular al Lago de Ilopango, en Cantón Apancino, a 500 metros del Turicentro Apulo. Ubicación privilegiada para desarrollo turístico e inmobiliario. $1,100,000. Cantón Apancino, Lago de Ilopango, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "13,974 m² / 20,000 v²",
      parqueos: "—",
    },
    features: ["2 manzanas (20,000 v²)", "Vista espectacular al Lago de Ilopango", "A 500 m del Turicentro Apulo, en dirección al Club Salvadoreño", "Ideal para hoteles y desarrollo inmobiliario"],
    images: ["images/listings/ilop/01.jpg", "images/listings/ilop/02.jpg", "images/listings/ilop/03.jpg", "images/listings/ilop/04.jpg", "images/listings/ilop/05.jpg", "images/listings/ilop/06.jpg"],
    video: "images/listings/ilop/video.mp4",
  },
  {
    id: "prop-flor",
    type: "propiedad",
    title: "Terreno con vista al Lago de Coatepeque",
    price: 135000,
    location: "Flor Amarilla",
    badges: ["Vista al lago"],
    operacion: "Venta",
    summary: "Terreno de 2,500 v² (1,747.5 m²) en Cantón Flor Amarilla, con vista espectacular al Lago de Coatepeque. Súper bien ubicado, sobre la calle…",
    description:
      "Terreno de 2,500 v² (1,747.5 m²) en Cantón Flor Amarilla, con vista espectacular al Lago de Coatepeque. Súper bien ubicado, sobre la calle rumbo a los restaurantes. $135,000. Cantón Flor Amarilla, El Salvador, con vista al Lago de Coatepeque.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "1,747.5 m² / 2,500 v²",
      parqueos: "—",
    },
    features: ["2,500 v² (1,747.5 m²)", "26 m de frente x 75 m de fondo", "Vista espectacular al Lago de Coatepeque", "Calle en dirección a los restaurantes, acceso en cualquier vehículo", "Terreno semiplano"],
    images: ["images/listings/flor/01.jpg", "images/listings/flor/02.jpg", "images/listings/flor/03.jpg", "images/listings/flor/04.jpg", "images/listings/flor/05.jpg", "images/listings/flor/06.jpg", "images/listings/flor/07.jpg", "images/listings/flor/08.jpg", "images/listings/flor/09.jpg", "images/listings/flor/10.jpg"],
  },
  {
    id: "prop-huiz",
    type: "propiedad",
    title: "6 manzanas en Huizúcar, junto a El Encanto Golf",
    price: 900000,
    location: "Huizúcar",
    badges: ["Junto a campo de golf"],
    operacion: "Venta",
    summary: "Terreno de 6 manzanas en Huizúcar, La Libertad, con vista al exclusivo complejo privado Residencial El Encanto Golf Country Club. Zona de…",
    description:
      "Terreno de 6 manzanas en Huizúcar, La Libertad, con vista al exclusivo complejo privado Residencial El Encanto Golf Country Club. Zona de alta plusvalía. $900,000 — $15 por vara². Huizúcar, La Libertad, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "41,922 m² / 60,000 v²",
      parqueos: "—",
    },
    features: ["6 manzanas (60,000 v²)", "Vista al complejo privado El Encanto Golf Country Club", "Factibilidad de agua potable y luz eléctrica", "Acceso en cualquier vehículo, a 20 minutos de la carretera al Puerto de La Libertad", "Topografía irregular", "Ideal para proyecto inmobiliario, apartamentos Airbnb o proyecto agrícola"],
    images: ["images/listings/huiz/01.jpg", "images/listings/huiz/02.jpg", "images/listings/huiz/03.jpg", "images/listings/huiz/04.jpg", "images/listings/huiz/05.jpg", "images/listings/huiz/06.jpg", "images/listings/huiz/07.jpg", "images/listings/huiz/08.jpg", "images/listings/huiz/09.jpg", "images/listings/huiz/10.jpg", "images/listings/huiz/11.jpg", "images/listings/huiz/12.jpg", "images/listings/huiz/13.jpg", "images/listings/huiz/14.jpg", "images/listings/huiz/15.jpg"],
    video: "images/listings/huiz/video.mp4",
  },
  {
    id: "prop-ahua",
    type: "propiedad",
    title: "20 manzanas en venta en Ahuachapán — Venta total",
    price: 175000,
    location: "Ahuachapán",
    badges: ["Requiere 4x4"],
    operacion: "Venta",
    summary: "Gran terreno de 20 manzanas en Ahuachapán, a 8 minutos de la carretera hacia Tacuba y 15 minutos del centro. Ideal para proyecto agrícola o…",
    description:
      "Gran terreno de 20 manzanas en Ahuachapán, a 8 minutos de la carretera hacia Tacuba y 15 minutos del centro. Ideal para proyecto agrícola o inversión. $175,000 — venta total únicamente. Ahuachapán, El Salvador. A 8 minutos de la carretera Ahuachapán–Tacuba y 15 minutos del centro.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "139,740 m² / 200,000 v²",
      parqueos: "—",
    },
    features: ["20 manzanas (200,000 v²)", "Topografía plana y semiplana", "Apta para paneles solares", "Agua mediante pozo artesanal", "Acceso con vehículo 4x4"],
    images: ["images/listings/ahua/01.jpg", "images/listings/ahua/02.jpg", "images/listings/ahua/03.jpg", "images/listings/ahua/04.jpg", "images/listings/ahua/05.jpg", "images/listings/ahua/06.jpg", "images/listings/ahua/07.jpg", "images/listings/ahua/08.jpg", "images/listings/ahua/09.jpg", "images/listings/ahua/10.jpg", "images/listings/ahua/11.jpg", "images/listings/ahua/12.jpg", "images/listings/ahua/13.jpg"],
    video: "images/listings/ahua/video.mp4",
  },
  {
    id: "prop-lagu",
    type: "propiedad",
    title: "18,000 v² con vista al Lago de Coatepeque",
    price: 92000,
    location: "Planes de la Laguna",
    badges: ["Vista al lago"],
    operacion: "Venta",
    summary: "Terreno de 18,000 v² (12,582 m²) en Cantón Planes de la Laguna, Santa Ana, con vista al Lago de Coatepeque. Gran extensión a un precio…",
    description:
      "Terreno de 18,000 v² (12,582 m²) en Cantón Planes de la Laguna, Santa Ana, con vista al Lago de Coatepeque. Gran extensión a un precio excelente. $92,000. Cantón Planes de la Laguna, Santa Ana, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "12,582 m² / 18,000 v²",
      parqueos: "—",
    },
    features: ["18,000 v² (12,582 m²)", "Vista al Lago de Coatepeque", "Acceso en cualquier vehículo (calle de tierra)", "Factibilidad de agua a 100 metros de distancia", "Luz mediante paneles solares", "Topografía semiplana"],
    images: ["images/listings/lagu/01.jpg", "images/listings/lagu/02.jpg", "images/listings/lagu/03.jpg", "images/listings/lagu/04.jpg", "images/listings/lagu/05.jpg", "images/listings/lagu/06.jpg", "images/listings/lagu/07.jpg", "images/listings/lagu/08.jpg", "images/listings/lagu/09.jpg", "images/listings/lagu/10.jpg", "images/listings/lagu/11.jpg", "images/listings/lagu/12.jpg", "images/listings/lagu/13.jpg", "images/listings/lagu/14.jpg"],
  },
  {
    id: "prop-atac",
    type: "propiedad",
    title: "17,000 v² 100% planos en Ataco — $55 la vara",
    price: 935000,
    location: "Ataco",
    badges: ["100% plano"],
    operacion: "Venta",
    summary: "Terreno de 17,000 v² (1.7 manzanas) a 3 minutos de la ciudad de Ataco, totalmente plano. Ideal para desarrollo, lotificación o proyecto…",
    description:
      "Terreno de 17,000 v² (1.7 manzanas) a 3 minutos de la ciudad de Ataco, totalmente plano. Ideal para desarrollo, lotificación o proyecto turístico. $935,000 ($55 por vara²). A 3 minutos de la ciudad de Ataco, Ahuachapán, El Salvador (Ruta de las Flores).",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "11,877 m² / 17,000 v²",
      parqueos: "—",
    },
    features: ["17,000 v² (1.7 manzanas)", "100% plano", "$55 por vara²", "A solo 3 minutos de la ciudad de Ataco", "Ideal para desarrollo, lotificación o proyecto turístico"],
    images: ["images/listings/atac/01.jpg"],
    video: "images/listings/atac/video.mp4",
  },
  {
    id: "prop-card",
    type: "propiedad",
    title: "Terreno cerca del Lago de Coatepeque — $130,000",
    price: 130000,
    location: "Cardedeu",
    badges: ["Con árboles frutales"],
    operacion: "Venta",
    summary: "Terreno de 4,000 v² (2,794.8 m²) a un costado de Cardedeu, a solo 200 metros del Lago de Coatepeque. Fresco y arbolado, ideal para casa de…",
    description:
      "Terreno de 4,000 v² (2,794.8 m²) a un costado de Cardedeu, a solo 200 metros del Lago de Coatepeque. Fresco y arbolado, ideal para casa de descanso. $130,000. A un costado de Cardedeu, cerca del Lago de Coatepeque, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,796 m² / 4,000 v²",
      parqueos: "—",
    },
    features: ["4,000 v² (2,794.8 m²)", "A solo 200 metros del Lago de Coatepeque", "Árboles frutales: café, mango, jocote y cacao", "A un costado de Cardedeu", "Ideal para casa de descanso o proyecto con vista"],
    images: ["images/listings/card/01.jpg", "images/listings/card/02.jpg", "images/listings/card/03.jpg", "images/listings/card/04.jpg", "images/listings/card/05.jpg", "images/listings/card/06.jpg"],
  },
  {
    id: "prop-juju",
    type: "propiedad",
    title: "335 manzanas en Jujutla — Finca de inversión",
    price: 2847500,
    location: "Jujutla",
    badges: ["Café en producción"],
    operacion: "Venta",
    summary: "Extraordinaria propiedad de 335 manzanas en Jujutla, Ahuachapán Sur, conformada por tres fincas (El Escondido, Copinula y Casa de Jesús),…",
    description:
      "Extraordinaria propiedad de 335 manzanas en Jujutla, Ahuachapán Sur, conformada por tres fincas (El Escondido, Copinula y Casa de Jesús), con café en producción, riqueza hídrica y minas de piedra laja. $8,500 por manzana — total $2,847,500. Venta total, ideal para inversión agroindustrial, café, minería de laja o desarrollo turístico. Jujutla, Ahuachapán Sur, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "2,340,645 m² / 3,350,000 v²",
      parqueos: "—",
    },
    features: ["335 manzanas (3,350,000 v² / 2,340,645 m²)", "100 manzanas de café cultivado en producción", "3 ríos y 6 cascadas dentro de la propiedad", "16 minas de piedra laja (5 sobre la carretera)", "Aproximadamente 2 km de frente sobre carretera", "Agua potable y energía eléctrica", "Acceso para todo tipo de vehículo"],
    images: ["images/listings/juju/01.jpg", "images/listings/juju/02.jpg", "images/listings/juju/03.jpg", "images/listings/juju/04.jpg", "images/listings/juju/05.jpg", "images/listings/juju/06.jpg", "images/listings/juju/07.jpg", "images/listings/juju/08.jpg"],
    video: "images/listings/juju/video.mp4",
  },
  {
    id: "prop-mora",
    type: "propiedad",
    title: "4 manzanas en Morazán — Ideal para ganadería",
    price: 140000,
    location: "Morazán",
    operacion: "Venta",
    summary: "Terreno de 4 manzanas en Caserío Santa Marta, Morazán, a 25 minutos de la carretera principal hacia San Francisco Gotera. Tierra fértil…",
    description:
      "Terreno de 4 manzanas en Caserío Santa Marta, Morazán, a 25 minutos de la carretera principal hacia San Francisco Gotera. Tierra fértil ideal para ganadería o cultivo. $140,000. Caserío Santa Marta, Morazán, El Salvador.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "27,948 m² / 40,000 v²",
      parqueos: "—",
    },
    features: ["4 manzanas (40,000 v²)", "Ideal para ganadería", "Topografía semiplana (quebrada en invierno)", "Factibilidad de luz eléctrica y agua potable a 200 m"],
    images: ["images/listings/mora/01.jpg", "images/listings/mora/02.jpg", "images/listings/mora/03.jpg", "images/listings/mora/04.jpg", "images/listings/mora/05.jpg", "images/listings/mora/06.jpg", "images/listings/mora/07.jpg"],
    video: "images/listings/mora/video.mp4",
  },
  {
    id: "prop-atac2",
    type: "propiedad",
    title: "Finca de café de altura en Ataco — 10 manzanas",
    price: 750000,
    location: "Ataco",
    badges: ["Vista al océano"],
    operacion: "Venta",
    summary: "Finca de café de 10 manzanas (100,000 v²) en Ataco, a 1,300 msnm, con vista al océano. Café de estricta altura, el más cotizado por su…",
    description:
      "Finca de café de 10 manzanas (100,000 v²) en Ataco, a 1,300 msnm, con vista al océano. Café de estricta altura, el más cotizado por su calidad. $750,000 ($75,000 por manzana). Ataco, Ahuachapán, El Salvador (Ruta de las Flores).",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "69,870 m² / 100,000 v²",
      parqueos: "—",
    },
    features: ["10 manzanas (100,000 v²)", "1,300 msnm, café de estricta altura", "Vista al océano", "$75,000 por manzana", "Ideal para producción de café de especialidad y ecoturismo"],
    images: ["images/listings/atac2/01.jpg", "images/listings/atac2/02.jpg", "images/listings/atac2/03.jpg", "images/listings/atac2/04.jpg", "images/listings/atac2/05.jpg", "images/listings/atac2/06.jpg", "images/listings/atac2/07.jpg", "images/listings/atac2/08.jpg", "images/listings/atac2/09.jpg", "images/listings/atac2/10.jpg", "images/listings/atac2/11.jpg", "images/listings/atac2/12.jpg", "images/listings/atac2/13.jpg"],
  },
  {
    id: "prop-cost",
    type: "propiedad",
    title: "Rancho a remodelar en Playa Costa Azul, con piscina",
    price: 180000,
    location: "Costa Azul",
    badges: ["Con piscina"],
    operacion: "Venta",
    summary: "Rancho de 600 m² (858 v²) en Playa Costa Azul, Sonsonate, a 300 metros del mar. Con piscina y listo para remodelar a tu gusto. Ideal para…",
    description:
      "Rancho de 600 m² (858 v²) en Playa Costa Azul, Sonsonate, a 300 metros del mar. Con piscina y listo para remodelar a tu gusto. Ideal para descansar con familia y amigos. $180,000. Playa Costa Azul, Sonsonate, El Salvador (a 300 m del mar, no frente al mar).",
    specs: {
      habitaciones: 2,
      banos: 1,
      areaConstruccion: "—",
      areaTerreno: "600 m² / 858 v²",
      parqueos: "—",
    },
    features: ["600 m² (858 v²)", "Amplia piscina (sin filtro)", "2 habitaciones y corredor amplio", "Baño con ducha y área de lavado", "Agua de pozo y de punta, energía eléctrica activa", "Amplio parqueo, fácil acceso, a 5 minutos de la playa"],
    images: ["images/listings/cost/01.jpg", "images/listings/cost/02.jpg", "images/listings/cost/03.jpg", "images/listings/cost/04.jpg", "images/listings/cost/05.jpg", "images/listings/cost/06.jpg", "images/listings/cost/07.jpg"],
    video: "images/listings/cost/video.mp4",
  },
  {
    id: "prop-delg",
    type: "propiedad",
    title: "Mesón comercial en Ciudad Delgado — $420,000",
    price: 420000,
    location: "Ciudad Delgado",
    badges: ["Uso comercial"],
    operacion: "Venta",
    summary: "Propiedad de uso comercial en Ciudad Delgado, con 8 habitaciones, cerca de la Avenida Juan Bertis y los juzgados. Zona de alto movimiento,…",
    description:
      "Propiedad de uso comercial en Ciudad Delgado, con 8 habitaciones, cerca de la Avenida Juan Bertis y los juzgados. Zona de alto movimiento, ideal para renta o negocio. $420,000. Ciudad Delgado, San Salvador, El Salvador, cerca de la Avenida Juan Bertis y los juzgados.",
    specs: {
      habitaciones: 8,
      banos: 3,
      areaConstruccion: "—",
      areaTerreno: "250 m² / 357 v²",
      parqueos: "—",
    },
    features: ["Uso comercial, frente de 10 m x 25 m de fondo", "8 habitaciones y 3 baños", "Cerca de la Avenida Juan Bertis y los juzgados", "Zona de alto movimiento", "Ideal para renta o negocio"],
    images: ["images/listings/delg/01.jpg", "images/listings/delg/02.jpg", "images/listings/delg/03.jpg", "images/listings/delg/04.jpg", "images/listings/delg/05.jpg"],
  },
  {
    id: "prop-acaj",
    type: "propiedad",
    title: "83 manzanas en Acajutla — Cañal en producción",
    price: 2241000,
    location: "Acajutla",
    badges: ["Cultivo en producción"],
    operacion: "Venta",
    summary: "Finca de 83 manzanas 100% planas en Acajutla, Sonsonate, con cultivo de caña, sistema de riego propio e infraestructura completa.…",
    description:
      "Finca de 83 manzanas 100% planas en Acajutla, Sonsonate, con cultivo de caña, sistema de riego propio e infraestructura completa. Agroindustria lista para operar. $27,000 por manzana — total $2,241,000. Venta total o desde un mínimo de 30 manzanas. Acajutla, Sonsonate, El Salvador, cerca de la gasolinera kilo 5.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "579,921 m² / 830,000 v²",
      parqueos: "—",
    },
    features: ["83 manzanas 100% planas (830,000 v²)", "Cultivo de caña con sistema de riego propio", "2 galeras grandes para tractores y maquinaria", "2 casas de seguridad", "Luz eléctrica y agua potable", "A 8 minutos de la carretera principal"],
    images: ["images/listings/acaj/01.jpg", "images/listings/acaj/02.jpg", "images/listings/acaj/03.jpg", "images/listings/acaj/04.jpg", "images/listings/acaj/05.jpg", "images/listings/acaj/06.jpg", "images/listings/acaj/07.jpg", "images/listings/acaj/08.jpg", "images/listings/acaj/09.jpg"],
    video: "images/listings/acaj/video.mp4",
  },
  {
    id: "prop-jaya",
    type: "propiedad",
    title: "Finca de café en Jayaque, con cabaña y mirador",
    price: 298000,
    location: "Jayaque",
    badges: ["Café en producción"],
    operacion: "Venta",
    summary: "Finca de café de 27,000 m² (39,000 v²) en Jayaque, a orilla de calle pavimentada, con vista espectacular a la ciudad. Cultivo en…",
    description:
      "Finca de café de 27,000 m² (39,000 v²) en Jayaque, a orilla de calle pavimentada, con vista espectacular a la ciudad. Cultivo en producción, cabaña y mirador. $298,000 (nuevo precio). Jayaque, El Salvador, a orilla de calle pavimentada.",
    specs: {
      habitaciones: "—",
      banos: 2,
      areaConstruccion: "—",
      areaTerreno: "27,000 m² / 39,000 v²",
      parqueos: "—",
    },
    features: ["27,000 m² (39,000 v²), 89% a orilla de calle", "Cabaña grande de 2 niveles de madera, con 2 baños completos", "Café Bourbon y Cuscatleco en producción", "Glorieta, sala de estar, sala de estudio y mirador con entorno construido", "Cisterna de 40 barriles, luz eléctrica y agua potable", "2 portones de acceso, bodega y casita para encargados", "Piso de laja", "Ideal también para proyecto urbano"],
    images: ["images/listings/jaya/01.jpg", "images/listings/jaya/02.jpg", "images/listings/jaya/03.jpg", "images/listings/jaya/04.jpg", "images/listings/jaya/05.jpg", "images/listings/jaya/06.jpg", "images/listings/jaya/07.jpg", "images/listings/jaya/08.jpg", "images/listings/jaya/09.jpg", "images/listings/jaya/10.jpg", "images/listings/jaya/11.jpg", "images/listings/jaya/12.jpg", "images/listings/jaya/13.jpg", "images/listings/jaya/14.jpg", "images/listings/jaya/15.jpg", "images/listings/jaya/16.jpg", "images/listings/jaya/17.jpg", "images/listings/jaya/18.jpg"],
  },
  {
    id: "prop-coat",
    type: "propiedad",
    title: "2 manzanas con vista al Lago de Coatepeque",
    price: 365000,
    location: "Coatepeque",
    badges: ["Vista al lago"],
    operacion: "Venta",
    summary: "Terreno de 2 manzanas con vista espectacular al Lago de Coatepeque, en Coatepeque, Santa Ana, en dirección al Cerro Verde y cerca del…",
    description:
      "Terreno de 2 manzanas con vista espectacular al Lago de Coatepeque, en Coatepeque, Santa Ana, en dirección al Cerro Verde y cerca del mirador El Anteojo. Ubicación turística de primer nivel. $365,000. Coatepeque, Santa Ana, El Salvador, en dirección al Cerro Verde.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "13,974 m² / 20,000 v²",
      parqueos: "—",
    },
    features: ["2 manzanas (20,000 v²)", "Vista espectacular al Lago de Coatepeque", "Acceso inmediato, a 200 m de la calle principal", "Ideal para torre de apartamentos, centro comercial, hoteles, restaurantes o cabañas"],
    images: ["images/listings/coat/01.jpg", "images/listings/coat/02.jpg", "images/listings/coat/03.jpg", "images/listings/coat/04.jpg", "images/listings/coat/05.jpg", "images/listings/coat/06.jpg", "images/listings/coat/07.jpg", "images/listings/coat/08.jpg", "images/listings/coat/09.jpg"],
  },
  {
    id: "prop-copa-3",
    type: "propiedad",
    title: "Lote en Copapayo — Tranquilidad y entorno natural",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. Tranquilidad y accesibilidad en un solo lugar. Perfecto para vivir rodeado de…",
    description:
      "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. Tranquilidad y accesibilidad en un solo lugar. Perfecto para vivir rodeado de naturaleza o para invertir. $29,000. Copapayo, El Salvador, cerca del río.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: ["842.5 m² (1,205 v²)", "Entorno natural, cerca del río", "Energía eléctrica disponible y agua potable", "Zona tranquila y de buen acceso", "Lote ya segregado; acceso por servidumbre en proyecto (plano), aún no construida"],
    images: ["images/listings/copa/02.jpg", "images/listings/copa/01.jpg", "images/listings/copa/03.jpg", "images/listings/copa/04.jpg", "images/listings/copa/05.jpg"],
    video: "images/listings/copa/video.mp4",
  },
  {
    id: "prop-copa-1",
    type: "propiedad",
    title: "Lote en Copapayo, cerca de la carretera",
    price: 29000,
    location: "Copapayo",
    operacion: "Venta",
    summary: "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. A pocos minutos de la carretera principal, en una zona tranquila y fresca.…",
    description:
      "Lote de 842.5 m² (1,205 v²) en Copapayo, cerca del río. A pocos minutos de la carretera principal, en una zona tranquila y fresca. Excelente opción para construir o invertir. $29,000. Copapayo, El Salvador, cerca del río.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "842.5 m² / 1,205 v²",
      parqueos: "—",
    },
    features: ["842.5 m² (1,205 v²)", "A pocos minutos de la carretera principal", "Energía eléctrica disponible y agua potable", "Zona tranquila y fresca, cerca del río", "Lote ya segregado; acceso por servidumbre privada en proyecto (plano), aún no construida"],
    images: ["images/listings/copa/02.jpg", "images/listings/copa/01.jpg", "images/listings/copa/03.jpg", "images/listings/copa/04.jpg", "images/listings/copa/05.jpg"],
    video: "images/listings/copa/video.mp4",
  },
  {
    id: "prop-cverdes2",
    type: "propiedad",
    title: "Casa totalmente remodelada en Campos Verdes 2, Lourdes Colón",
    price: 69000,
    location: "Lourdes Colón",
    badges: ["Remodelada"],
    operacion: "Venta",
    summary: "Casa totalmente remodelada en Campos Verdes 2, Lourdes Colón. Acabados modernos, techo más alto para un ambiente más fresco, lista para entrar…",
    description:
      "Casa totalmente remodelada en Campos Verdes 2, Lourdes Colón. 5 m de ancho por 12.50 m de largo. 2 habitaciones, sala, comedor, cocina, 1 baño completo, cochera para 1 vehículo, terraza, patio techado, lavadero y tendedero, jardincito. Techo más alto para un ambiente más fresco y acabados modernos. $69,000.",
    specs: {
      habitaciones: 2,
      banos: 1,
      areaConstruccion: "—",
      areaTerreno: "5 x 12.50 m",
      parqueos: "1",
    },
    features: ["5 m de ancho por 12.50 m de largo", "2 habitaciones", "Sala y comedor", "Cocina", "1 baño completo", "Cochera para 1 vehículo", "Terraza y patio techado", "Lavadero y tendedero", "Jardincito", "Techo más alto — ambiente más fresco", "Acabados modernos"],
    images: ["images/listings/cverdes2/01.jpg", "images/listings/cverdes2/02.jpg", "images/listings/cverdes2/03.jpg", "images/listings/cverdes2/04.jpg", "images/listings/cverdes2/05.jpg", "images/listings/cverdes2/06.jpg"],
  },
  {
    id: "prop-papalon",
    type: "propiedad",
    title: "Terreno de 200 m² en El Papalón, Santa Rosa de Lima",
    price: 44000,
    location: "Santa Rosa de Lima, La Unión",
    operacion: "Venta",
    summary: "Terreno de 10 x 20 m (200 m²) en El Papalón, Santa Rosa de Lima, La Unión. Ideal para construir casa. A 300 metros de la carretera principal…",
    description:
      "Terreno de 10 x 20 m (200 m²) en El Papalón, Santa Rosa de Lima, La Unión. Ideal para construir casa. Con factibilidad de luz eléctrica y agua potable, a 300 metros de la carretera principal, excelente ubicación. $44,000.",
    specs: {
      habitaciones: "—",
      banos: "—",
      areaConstruccion: "—",
      areaTerreno: "200 m² (10 x 20 m)",
      parqueos: "—",
    },
    features: ["200 m² (10 x 20 m)", "Ideal para construir casa", "Factibilidad de luz eléctrica y agua potable", "A 300 metros de la carretera principal", "Excelente ubicación"],
    images: ["images/listings/papalon/01.jpg", "images/listings/papalon/02.jpg", "images/listings/papalon/03.jpg", "images/listings/papalon/04.jpg", "images/listings/papalon/05.jpg"],
  },

  // ---------------- VEHÍCULOS ----------------
  {
    id: "veh-4runnertrd2024",
    type: "vehiculo",
    title: "Toyota 4Runner TRD Off Road Premium 2024 4x4 — Importada de EE.UU.",
    price: 44000,
    location: "Coordinar por WhatsApp",
    badges: ["4x4", "Importado de EE.UU."],
    operacion: "Venta",
    summary: "Toyota 4Runner TRD Off Road Premium 2024, importada de Estados Unidos, 4x4 automática, 34,000 millas recorridas. Rines especiales de lujo, doble…",
    description:
      "Toyota 4Runner TRD Off Road Premium 2024, importada de Estados Unidos, 4x4 automática, 34,000 millas recorridas. Rines especiales de lujo, doble aire acondicionado, tapicería en cuero. Motor 4.0, 6 cilindros, gasolina. Cero detalles, a toda revisión mecánica. Se recibe vehículo a cuenta a menor valor. $44,000.",
    specs: {
      anio: 2024,
      kilometraje: "34,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "4.0, 6 cilindros",
    },
    features: ["Importada de Estados Unidos, 4x4 automática", "34,000 millas recorridas", "Rines especiales de lujo", "Doble aire acondicionado", "Tapicería en cuero", "Se recibe vehículo a cuenta a menor valor"],
    images: ["images/listings/4runnertrd2024/01.jpg", "images/listings/4runnertrd2024/02.jpg", "images/listings/4runnertrd2024/03.jpg", "images/listings/4runnertrd2024/04.jpg", "images/listings/4runnertrd2024/05.jpg", "images/listings/4runnertrd2024/06.jpg", "images/listings/4runnertrd2024/07.jpg", "images/listings/4runnertrd2024/08.jpg", "images/listings/4runnertrd2024/09.jpg", "images/listings/4runnertrd2024/10.jpg", "images/listings/4runnertrd2024/11.jpg"],
  },
  {
    id: "veh-pathsl2025",
    type: "vehiculo",
    title: "Nissan Pathfinder SL 2025 — Línea nueva, 3 filas, full cuero",
    price: 36000,
    location: "Coordinar por WhatsApp",
    badges: ["Línea nueva"],
    operacion: "Venta",
    summary: "Nissan Pathfinder SL línea nueva 2025, 3 filas de asientos, full cuero y techo panorámico, 41,000 millas recorridas. Rines súper especiales de…",
    description:
      "Nissan Pathfinder SL línea nueva 2025, 3 filas de asientos, full cuero y techo panorámico, 41,000 millas recorridas. Tapicería en full cuero, rines súper especiales de lujo, triple aire acondicionado. Cero detalles, a toda revisión mecánica. Se brinda garantía de 6 meses. $36,000.",
    specs: {
      anio: 2025,
      kilometraje: "41,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "—",
    },
    features: ["Línea nueva, 3 filas de asientos", "Full cuero y techo panorámico", "41,000 millas recorridas", "Rines súper especiales de lujo", "Triple aire acondicionado", "Garantía de 6 meses"],
    images: ["images/listings/pathsl2025/01.jpg", "images/listings/pathsl2025/02.jpg", "images/listings/pathsl2025/03.jpg", "images/listings/pathsl2025/04.jpg", "images/listings/pathsl2025/05.jpg", "images/listings/pathsl2025/06.jpg", "images/listings/pathsl2025/07.jpg", "images/listings/pathsl2025/08.jpg", "images/listings/pathsl2025/09.jpg", "images/listings/pathsl2025/10.jpg"],
  },
  {
    id: "veh-frontpro4x2025",
    type: "vehiculo",
    title: "Nissan Frontier PRO-4X 2025 — Línea nueva 4x4",
    price: 33500,
    location: "Coordinar por WhatsApp",
    badges: ["4x4", "Línea nueva"],
    operacion: "Venta",
    summary: "Nissan Frontier PRO-4X 2025, línea nueva, 4x4 automático, full extras. Rines súper especiales de lujo, doble aire acondicionado, encendido de…",
    description:
      "Nissan Frontier PRO-4X 2025, línea nueva, 4x4 automático, full extras. Rines súper especiales de lujo, doble aire acondicionado, encendido de botón con llave de proximidad, pantalla de navegación táctil, sonido premium, protector de cama. Motor 3.8, 6 cilindros, gasolina. Cero detalles, a toda revisión mecánica. $33,500.",
    specs: {
      anio: 2025,
      kilometraje: "—",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "3.8, 6 cilindros",
    },
    features: ["Línea nueva, 4x4 automático", "Rines súper especiales de lujo", "Doble aire acondicionado", "Encendido de botón con llave de proximidad", "Pantalla de navegación táctil", "Sonido premium", "Protector de cama"],
    images: ["images/listings/frontpro4x2025/01.jpg", "images/listings/frontpro4x2025/02.jpg", "images/listings/frontpro4x2025/03.jpg", "images/listings/frontpro4x2025/04.jpg", "images/listings/frontpro4x2025/05.jpg", "images/listings/frontpro4x2025/06.jpg", "images/listings/frontpro4x2025/07.jpg", "images/listings/frontpro4x2025/08.jpg", "images/listings/frontpro4x2025/09.jpg", "images/listings/frontpro4x2025/10.jpg", "images/listings/frontpro4x2025/11.jpg"],
  },
  {
    id: "veh-broncosport2022",
    type: "vehiculo",
    title: "Ford Bronco Sport Outerbanks 2022 4x4 — Importada de EE.UU.",
    price: 21950,
    location: "Coordinar por WhatsApp",
    badges: ["4x4", "Importado de EE.UU."],
    operacion: "Venta",
    summary: "Ford Bronco Sport Outerbanks 2022 4x4, importada de Estados Unidos, apenas 1,400 millas recorridas, como nueva. Sunroof, tapicería con detalles…",
    description:
      "Ford Bronco Sport Outerbanks 2022 4x4, importada de Estados Unidos, apenas 1,400 millas recorridas, como nueva. Sunroof, tapicería con detalles de cuero y tela, pantalla de navegación táctil, rines súper especiales de lujo. Motor 1.5 turbo de 3 cilindros, gasolina. Full extras. Venta cash de un solo pago, no se aceptan cambios. También financiamiento con 40% de prima ($9,200) y cuotas aproximadas de $380 por 5 años. $21,950.",
    specs: {
      anio: 2022,
      kilometraje: "1,400 millas",
      transmision: "—",
      combustible: "Gasolina",
      motor: "1.5 turbo, 3 cilindros",
    },
    features: ["Importada de Estados Unidos, apenas 1,400 millas — como nueva", "Sunroof", "Tapicería con detalles de cuero y tela", "Pantalla de navegación táctil", "Rines súper especiales de lujo", "Full extras"],
    images: ["images/listings/broncosport2022/01.jpg", "images/listings/broncosport2022/02.jpg", "images/listings/broncosport2022/03.jpg", "images/listings/broncosport2022/04.jpg", "images/listings/broncosport2022/05.jpg", "images/listings/broncosport2022/06.jpg", "images/listings/broncosport2022/07.jpg", "images/listings/broncosport2022/08.jpg", "images/listings/broncosport2022/09.jpg", "images/listings/broncosport2022/10.jpg", "images/listings/broncosport2022/11.jpg"],
  },
  {
    id: "veh-npfront2021",
    type: "vehiculo",
    title: "Nissan Frontier NP300 2021 4x4 — Turbo diésel",
    price: 26000,
    location: "Coordinar por WhatsApp",
    badges: ["4x4"],
    operacion: "Venta",
    summary: "Nissan Frontier NP300 2021, estándar 4x4, turbo diésel, de agencia. Un solo dueño, 137,000 km recorridos. Rines especiales, aire acondicionado…",
    description:
      "Nissan Frontier NP300 2021, estándar 4x4, turbo diésel, de agencia. Un solo dueño con 137,000 kilómetros recorridos. Rines especiales de lujo, aire acondicionado, pantalla de navegación, llantas en muy buen estado, protector de cama y vidrios eléctricos. Venta directa cash o al crédito, no se aceptan cambios. $26,000.",
    specs: {
      anio: 2021,
      kilometraje: "137,000 km",
      transmision: "Estándar",
      combustible: "Diésel",
      motor: "Turbo diésel",
    },
    features: ["Un solo dueño, 137,000 km recorridos", "Estándar, 4x4", "Rines especiales de lujo", "Aire acondicionado", "Pantalla de navegación", "Protector de cama", "Vidrios eléctricos", "Llantas en muy buen estado"],
    images: ["images/listings/npfront2021/01.jpg", "images/listings/npfront2021/02.jpg", "images/listings/npfront2021/03.jpg", "images/listings/npfront2021/04.jpg", "images/listings/npfront2021/05.jpg", "images/listings/npfront2021/06.jpg", "images/listings/npfront2021/07.jpg", "images/listings/npfront2021/08.jpg", "images/listings/npfront2021/09.jpg", "images/listings/npfront2021/10.jpg", "images/listings/npfront2021/11.jpg"],
  },
  {
    id: "veh-cfmo2020",
    type: "vehiculo",
    title: "Cuadrimoto CF Moto 2020 en venta — El Salvador",
    price: 8500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Cuadrimoto (ATV) CF Moto modelo 2020 en excelente estado. Ideal para campo, finca y aventura off-road.",
    description:
      "Cuadrimoto (ATV) CF Moto modelo 2020 en excelente estado. Ideal para campo, finca y aventura off-road. $8,500",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Marca CF Moto, modelo 2020", "Excelente estado", "Ideal para terreno rústico y trabajo"],
    images: ["images/listings/cfmo2020/01.jpg", "images/listings/cfmo2020/02.jpg", "images/listings/cfmo2020/03.jpg", "images/listings/cfmo2020/04.jpg", "images/listings/cfmo2020/05.jpg", "images/listings/cfmo2020/06.jpg", "images/listings/cfmo2020/07.jpg", "images/listings/cfmo2020/08.jpg", "images/listings/cfmo2020/09.jpg", "images/listings/cfmo2020/10.jpg", "images/listings/cfmo2020/11.jpg", "images/listings/cfmo2020/12.jpg", "images/listings/cfmo2020/13.jpg", "images/listings/cfmo2020/14.jpg", "images/listings/cfmo2020/15.jpg", "images/listings/cfmo2020/16.jpg", "images/listings/cfmo2020/17.jpg", "images/listings/cfmo2020/18.jpg", "images/listings/cfmo2020/19.jpg", "images/listings/cfmo2020/20.jpg"],
  },
  {
    id: "veh-acco2020",
    type: "vehiculo",
    title: "Honda Accord 2020 en venta — El Salvador",
    price: 19900,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Sedán Honda Accord modelo 2020 en excelente estado. Confort, estilo y la confiabilidad característica de Honda.",
    description:
      "Sedán Honda Accord modelo 2020 en excelente estado. Confort, estilo y la confiabilidad característica de Honda. $19,900",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Honda Accord 2020", "Sedán, alto confort", "Excelente estado"],
    images: ["images/listings/acco2020/01.jpg", "images/listings/acco2020/02.jpg", "images/listings/acco2020/03.jpg", "images/listings/acco2020/04.jpg", "images/listings/acco2020/05.jpg", "images/listings/acco2020/06.jpg", "images/listings/acco2020/07.jpg", "images/listings/acco2020/08.jpg", "images/listings/acco2020/09.jpg", "images/listings/acco2020/10.jpg", "images/listings/acco2020/11.jpg", "images/listings/acco2020/12.jpg"],
  },
  {
    id: "veh-q3sl2018",
    type: "vehiculo",
    title: "Audi Q3 S Line 2018 Quattro 4x4",
    price: 16500,
    location: "Coordinar por WhatsApp",
    badges: ["Importado de EE.UU.", "4x4"],
    operacion: "Venta",
    summary: "SUV Audi Q3 S Line 2018 con tracción Quattro (4x4), importada de Estados Unidos y a toda revisión mecánica profesional. Lujo europeo súper…",
    description:
      "SUV Audi Q3 S Line 2018 con tracción Quattro (4x4), importada de Estados Unidos y a toda revisión mecánica profesional. Lujo europeo súper económico. $16,500 (solo venta de contado, no se aceptan cambios)",
    specs: {
      anio: 2018,
      kilometraje: "120,700 km",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Motor 2.0 Turbo gasolina, 4 cilindros", "Tracción Quattro 4x4", "Tapicería en cuero y techo panorámico", "Encendido de botón con llave de proximidad", "Freno de mano electrónico y baúl eléctrico", "Todas las bolsas de aire en buen estado", "75,000 millas recorridas"],
    images: ["images/listings/q3sl2018/01.jpg", "images/listings/q3sl2018/02.jpg", "images/listings/q3sl2018/03.jpg", "images/listings/q3sl2018/04.jpg", "images/listings/q3sl2018/05.jpg", "images/listings/q3sl2018/06.jpg", "images/listings/q3sl2018/07.jpg", "images/listings/q3sl2018/08.jpg", "images/listings/q3sl2018/09.jpg", "images/listings/q3sl2018/10.jpg", "images/listings/q3sl2018/11.jpg", "images/listings/q3sl2018/12.jpg", "images/listings/q3sl2018/13.jpg"],
  },
  {
    id: "veh-mazd2016",
    type: "vehiculo",
    title: "Mazda 3 2016 en venta — El Salvador",
    price: 7900,
    location: "Coordinar por WhatsApp",
    badges: ["Con financiamiento"],
    operacion: "Venta",
    summary: "Sedán Mazda 3 modelo 2016 en buen estado, deportivo y económico. Con opción de financiamiento. $7,900 Financiamiento: Disponible — prima…",
    description:
      "Sedán Mazda 3 modelo 2016 en buen estado, deportivo y económico. Con opción de financiamiento. $7,900 Financiamiento: Disponible — prima desde $3,160.",
    specs: {
      anio: 2016,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Mazda 3 2016", "Sedán deportivo y económico", "Buen estado"],
    images: ["images/listings/mazd2016/01.jpg", "images/listings/mazd2016/02.jpg", "images/listings/mazd2016/03.jpg", "images/listings/mazd2016/04.jpg", "images/listings/mazd2016/05.jpg", "images/listings/mazd2016/06.jpg"],
  },
  {
    id: "veh-fron2021",
    type: "vehiculo",
    title: "Nissan Frontier 2021 King Cab",
    price: 13500,
    location: "Coordinar por WhatsApp",
    badges: ["Con financiamiento"],
    operacion: "Venta",
    summary: "Pick-up Nissan Frontier 2021 cabina King Cab en excelente estado. Ideal para trabajo y uso diario. Con opción de financiamiento. $13,500…",
    description:
      "Pick-up Nissan Frontier 2021 cabina King Cab en excelente estado. Ideal para trabajo y uso diario. Con opción de financiamiento. $13,500 Financiamiento: Disponible — prima desde $5,400 (más $250 de gastos administrativos).",
    specs: {
      anio: 2021,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Nissan Frontier 2021", "Cabina King Cab", "Excelente estado"],
    images: ["images/listings/fron2021/01.jpg", "images/listings/fron2021/02.jpg", "images/listings/fron2021/03.jpg", "images/listings/fron2021/04.jpg", "images/listings/fron2021/05.jpg", "images/listings/fron2021/06.jpg", "images/listings/fron2021/07.jpg", "images/listings/fron2021/08.jpg", "images/listings/fron2021/09.jpg", "images/listings/fron2021/10.jpg", "images/listings/fron2021/11.jpg", "images/listings/fron2021/12.jpg", "images/listings/fron2021/13.jpg"],
    video: "images/listings/fron2021/video.mp4",
  },
  {
    id: "veh-outl2020",
    type: "vehiculo",
    title: "Mitsubishi Outlander 2020 en venta — El Salvador",
    price: 13500,
    location: "Coordinar por WhatsApp",
    badges: ["Con financiamiento"],
    operacion: "Venta",
    summary: "SUV Mitsubishi Outlander modelo 2020 en excelente estado. Amplio, cómodo y seguro, ideal para familia. Con opción de financiamiento.…",
    description:
      "SUV Mitsubishi Outlander modelo 2020 en excelente estado. Amplio, cómodo y seguro, ideal para familia. Con opción de financiamiento. $13,500 Financiamiento: Disponible — prima desde $5,500 (más $250 de gastos administrativos).",
    specs: {
      anio: 2020,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Mitsubishi Outlander 2020", "SUV familiar, amplio y cómodo", "Excelente estado"],
    images: ["images/listings/outl2020/01.jpg", "images/listings/outl2020/02.jpg", "images/listings/outl2020/03.jpg", "images/listings/outl2020/04.jpg", "images/listings/outl2020/05.jpg", "images/listings/outl2020/06.jpg", "images/listings/outl2020/07.jpg", "images/listings/outl2020/08.jpg", "images/listings/outl2020/09.jpg", "images/listings/outl2020/10.jpg", "images/listings/outl2020/11.jpg", "images/listings/outl2020/12.jpg", "images/listings/outl2020/13.jpg", "images/listings/outl2020/15.jpg", "images/listings/outl2020/16.jpg", "images/listings/outl2020/17.jpg", "images/listings/outl2020/18.jpg", "images/listings/outl2020/19.jpg", "images/listings/outl2020/20.jpg", "images/listings/outl2020/21.jpg", "images/listings/outl2020/22.jpg", "images/listings/outl2020/23.jpg", "images/listings/outl2020/24.jpg", "images/listings/outl2020/25.jpg"],
  },
  {
    id: "veh-kona2023",
    type: "vehiculo",
    title: "Hyundai Kona AWD (4x4) 2023 en venta — El Salvador",
    price: 15500,
    location: "Coordinar por WhatsApp",
    badges: ["Con financiamiento", "AWD"],
    operacion: "Venta",
    summary: "SUV compacto Hyundai Kona con tracción integral AWD, modelo 2023 en excelente estado. Moderno y tecnológico. Con opción de financiamiento.…",
    description:
      "SUV compacto Hyundai Kona con tracción integral AWD, modelo 2023 en excelente estado. Moderno y tecnológico. Con opción de financiamiento. $15,500 Financiamiento: Disponible — prima desde $6,200.",
    specs: {
      anio: 2023,
      kilometraje: "—",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Hyundai Kona AWD (4x4) 2023", "Tracción integral AWD", "Modelo reciente, excelente estado"],
    images: ["images/listings/kona2023/01.jpg", "images/listings/kona2023/02.jpg", "images/listings/kona2023/03.jpg", "images/listings/kona2023/04.jpg", "images/listings/kona2023/05.jpg", "images/listings/kona2023/06.jpg", "images/listings/kona2023/07.jpg", "images/listings/kona2023/08.jpg", "images/listings/kona2023/09.jpg"],
  },
  {
    id: "veh-l2002013",
    type: "vehiculo",
    title: "Mitsubishi L200 2013 en venta — El Salvador",
    price: 20000,
    location: "Coordinar por WhatsApp",
    badges: ["Nunca chocado"],
    operacion: "Venta",
    summary: "Pick-up Mitsubishi L200 Sportero 2013, de agencia y nunca chocado. Resistente y confiable, ideal para trabajo, finca y uso diario.",
    description:
      "Pick-up Mitsubishi L200 Sportero 2013, de agencia y nunca chocado, con 192,000 kilómetros recorridos. Equipada con rines y sunroof. Resistente y confiable, ideal para trabajo, finca y uso diario. $20,000",
    specs: {
      anio: 2013,
      kilometraje: "192,000 km",
      transmision: "—",
      combustible: "—",
      motor: "—",
    },
    features: ["Mitsubishi L200 Sportero 2013", "De agencia, nunca chocado", "192,000 km recorridos", "Rines y sunroof", "Pick-up de trabajo, resistente"],
    images: ["images/listings/l2002013/01.jpg", "images/listings/l2002013/02.jpg", "images/listings/l2002013/03.jpg", "images/listings/l2002013/04.jpg", "images/listings/l2002013/05.jpg", "images/listings/l2002013/06.jpg", "images/listings/l2002013/07.jpg", "images/listings/l2002013/08.jpg", "images/listings/l2002013/09.jpg", "images/listings/l2002013/10.jpg", "images/listings/l2002013/11.jpg", "images/listings/l2002013/12.jpg", "images/listings/l2002013/13.jpg", "images/listings/l2002013/14.jpg", "images/listings/l2002013/15.jpg", "images/listings/l2002013/16.jpg", "images/listings/l2002013/17.jpg", "images/listings/l2002013/18.jpg", "images/listings/l2002013/19.jpg", "images/listings/l2002013/20.jpg", "images/listings/l2002013/21.jpg", "images/listings/l2002013/22.jpg", "images/listings/l2002013/23.jpg", "images/listings/l2002013/24.jpg", "images/listings/l2002013/25.jpg", "images/listings/l2002013/26.jpg"],
    video: "images/listings/l2002013/video.mp4",
  },
  // ---------------- VEHÍCULOS NUEVOS (agosto 2026) ----------------
  {
    id: "veh-l2002025",
    type: "vehiculo",
    title: "Mitsubishi L200 2025 4x4 — Usado como nuevo",
    price: 34000,
    location: "Ciudad Merliot",
    operacion: "Venta",
    summary: "Mitsubishi L200 línea nueva 2025, 4x4 estándar, usado como nuevo con 38,000 km recorridos. Rines especiales, cámara, roll-bar, todas bolsas de aire…",
    description:
      "Mitsubishi L200 línea nueva 2025, 4x4 estándar, usado como nuevo con 38,000 km recorridos. Rines especiales, cámara, roll-bar, todas bolsas de aire buenas, nunca chocado. $34,000 cash o crédito con 20% de prima.",
    specs: {
      anio: "2025",
      kilometraje: "38,000 km",
      transmision: "Estándar",
      combustible: "Diésel",
      motor: "—",
    },
    features: ["38,000 km recorridos, usado como nuevo", "Rines especiales, cámara, roll-bar", "Todas bolsas de aire buenas, nunca chocado"],
    images: ["images/listings/l2002025/01.jpg", "images/listings/l2002025/02.jpg", "images/listings/l2002025/03.jpg", "images/listings/l2002025/04.jpg", "images/listings/l2002025/05.jpg", "images/listings/l2002025/06.jpg", "images/listings/l2002025/07.jpg", "images/listings/l2002025/08.jpg", "images/listings/l2002025/09.jpg", "images/listings/l2002025/10.jpg", "images/listings/l2002025/11.jpg", "images/listings/l2002025/12.jpg"],
  },
  {
    id: "veh-f650volq",
    type: "vehiculo",
    title: "Ford F650 Super Duty 2013 — Volqueta",
    price: 26000,
    location: "Santa Tecla",
    operacion: "Venta",
    summary: "Volqueta Ford F650 Super Duty 2013, motor turbo diésel, medida de cajón de 9 metros cúbicos, con emisión de gases y expertise en toda la papelería…",
    description:
      "Volqueta Ford F650 Super Duty 2013, motor turbo diésel, medida de cajón de 9 metros cúbicos, con emisión de gases y expertise en toda la papelería legal. $26,000 cash o crédito, cuota máx. $500/mes. Se muestra en oficina de Santa Tecla, camino a la Pampa, El Volcán.",
    specs: {
      anio: "2013",
      kilometraje: "—",
      transmision: "—",
      combustible: "Diésel",
      motor: "Turbo diésel",
    },
    features: ["Cajón de 9 metros cúbicos", "Motor turbo diésel", "Toda la papelería legal en regla"],
    images: ["images/listings/f650volq/01.jpg", "images/listings/f650volq/02.jpg", "images/listings/f650volq/03.jpg", "images/listings/f650volq/04.jpg", "images/listings/f650volq/05.jpg", "images/listings/f650volq/06.jpg", "images/listings/f650volq/07.jpg", "images/listings/f650volq/08.jpg", "images/listings/f650volq/09.jpg"],
  },
  {
    id: "veh-outlsport2025",
    type: "vehiculo",
    title: "Mitsubishi Outlander Sport 2025 4x4 — Importada",
    price: 21500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Mitsubishi Outlander Sport 2025 4x4, importada, muy poco millaje, a toda revisión mecánica. Garantía de 6 meses o primer mantenimiento gratis.…",
    description:
      "Mitsubishi Outlander Sport 2025 4x4, importada, muy poco millaje, a toda revisión mecánica. Garantía de 6 meses o primer mantenimiento gratis. $21,500 cash o crédito con EasyCar, 40% de prima.",
    specs: {
      anio: "2025",
      kilometraje: "—",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "4 cilindros",
    },
    features: ["Importada, muy poco millaje", "Garantía 6 meses / 1er mantenimiento gratis", "A toda revisión mecánica"],
    images: ["images/listings/outlsport2025/01.jpg", "images/listings/outlsport2025/02.jpg", "images/listings/outlsport2025/03.jpg", "images/listings/outlsport2025/04.jpg", "images/listings/outlsport2025/05.jpg", "images/listings/outlsport2025/06.jpg", "images/listings/outlsport2025/07.jpg", "images/listings/outlsport2025/08.jpg", "images/listings/outlsport2025/09.jpg"],
  },
  {
    id: "veh-outlsport2024",
    type: "vehiculo",
    title: "Mitsubishi Outlander Sport 2024 4x4 — Importada",
    price: 20500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Mitsubishi Outlander Sport 2024 4x4, importada, a toda revisión mecánica, con garantía de 6 meses antes de entregar la camioneta. $20,500 cash o…",
    description:
      "Mitsubishi Outlander Sport 2024 4x4, importada, a toda revisión mecánica, con garantía de 6 meses antes de entregar la camioneta. $20,500 cash o crédito con EasyCar, 40% de prima.",
    specs: {
      anio: "2024",
      kilometraje: "—",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "4 cilindros",
    },
    features: ["Importada, a toda revisión mecánica", "Garantía total 6 meses antes de entrega"],
    images: ["images/listings/outlsport2024/01.jpg", "images/listings/outlsport2024/02.jpg", "images/listings/outlsport2024/03.jpg", "images/listings/outlsport2024/04.jpg", "images/listings/outlsport2024/05.jpg", "images/listings/outlsport2024/06.jpg", "images/listings/outlsport2024/07.jpg", "images/listings/outlsport2024/08.jpg", "images/listings/outlsport2024/09.jpg", "images/listings/outlsport2024/10.jpg"],
  },
  {
    id: "veh-suzgv2024",
    type: "vehiculo",
    title: "Suzuki Grand Vitara 2024 híbrida — De agencia",
    price: 24554,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Suzuki Grand Vitara 2024 de agencia, híbrida, 38,000 km recorridos, garantía de agencia hasta 100,000 km. Motor 1.5 híbrido, techo panorámico,…",
    description:
      "Suzuki Grand Vitara 2024 de agencia, híbrida, 38,000 km recorridos, garantía de agencia hasta 100,000 km. Motor 1.5 híbrido, techo panorámico, cargador inalámbrico, asientos en cuero. $24,554, no se aceptan cambios. Crédito solo con Credi Q.",
    specs: {
      anio: "2024",
      kilometraje: "38,000 km",
      transmision: "Automática",
      combustible: "Híbrido",
      motor: "1.5 híbrido",
    },
    features: ["De agencia, garantía hasta 100,000 km", "Techo panorámico, cargador de celular inalámbrico", "Asientos en cuero"],
    images: ["images/listings/suzgv2024/01.jpg", "images/listings/suzgv2024/02.jpg", "images/listings/suzgv2024/03.jpg", "images/listings/suzgv2024/04.jpg", "images/listings/suzgv2024/05.jpg", "images/listings/suzgv2024/06.jpg", "images/listings/suzgv2024/07.jpg", "images/listings/suzgv2024/08.jpg", "images/listings/suzgv2024/09.jpg", "images/listings/suzgv2024/10.jpg", "images/listings/suzgv2024/11.jpg", "images/listings/suzgv2024/12.jpg"],
  },
  {
    id: "veh-f1502022b",
    type: "vehiculo",
    title: "Ford F-150 2022 4x4 — Importada",
    price: 32000,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Ford F-150 4x4 automática, importada, motor de 6 cilindros gasolina, doble cabina, 40,000 millas recorridas. Pantalla de navegación táctil, sonido…",
    description:
      "Ford F-150 4x4 automática, importada, motor de 6 cilindros gasolina, doble cabina, 40,000 millas recorridas. Pantalla de navegación táctil, sonido premium, encendido de botón, rines especiales de lujo, paquete eléctrico, doble sistema de aire acondicionado. $32,000, se recibe vehículo a cuenta a menor valor de mercado.",
    specs: {
      anio: "2022",
      kilometraje: "40,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "6 cilindros",
    },
    features: ["Doble cabina, 40,000 millas recorridas", "Pantalla de navegación táctil, sonido premium", "Rines especiales de lujo, paquete eléctrico"],
    images: [],
  },
  {
    id: "veh-kona2022a",
    type: "vehiculo",
    title: "Hyundai Kona 2022 2WD",
    price: 15500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Hyundai Kona 2022 importada, 2WD, todas las bolsas de aire buenas, encendido de botón con llave de proximidad, 37,000 millas recorridas. $15,500, o…",
    description:
      "Hyundai Kona 2022 importada, 2WD, todas las bolsas de aire buenas, encendido de botón con llave de proximidad, 37,000 millas recorridas. $15,500, o crédito con 40% de prima, cuotas aprox. $399/mes por 5 años.",
    specs: {
      anio: "2022",
      kilometraje: "37,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "—",
    },
    features: ["37,000 millas recorridas", "Todas bolsas de aire buenas", "Encendido de botón con llave de proximidad"],
    images: ["images/listings/kona2022a/01.jpg", "images/listings/kona2022a/02.jpg", "images/listings/kona2022a/03.jpg", "images/listings/kona2022a/04.jpg", "images/listings/kona2022a/05.jpg", "images/listings/kona2022a/06.jpg", "images/listings/kona2022a/07.jpg", "images/listings/kona2022a/08.jpg", "images/listings/kona2022a/09.jpg", "images/listings/kona2022a/10.jpg", "images/listings/kona2022a/11.jpg", "images/listings/kona2022a/12.jpg"],
  },
  {
    id: "veh-hiluxrevo2018",
    type: "vehiculo",
    title: "Toyota Hilux Revo 2018 — Automática, full extras",
    price: 35000,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Toyota Hilux Revo 2018 automática, full extras, 240,000 km recorridos, todas bolsas de aire buenas. Motor 2.7 turbo diésel, rines especiales de 20…",
    description:
      "Toyota Hilux Revo 2018 automática, full extras, 240,000 km recorridos, todas bolsas de aire buenas. Motor 2.7 turbo diésel, rines especiales de 20 pulgadas, kit de cromos completo con estribos y cobertor de cama. $35,000 cash, no se acepta vehículo a cuenta. Crédito solo con Credi Q, 20% de prima.",
    specs: {
      anio: "2018",
      kilometraje: "240,000 km",
      transmision: "Automática",
      combustible: "Diésel",
      motor: "2.7 turbo",
    },
    features: ["240,000 km, full extras", "Motor 2.7 turbo diésel", "Rines especiales 20\", kit de cromos, cobertor de cama"],
    images: ["images/listings/hiluxrevo2018/01.jpg", "images/listings/hiluxrevo2018/02.jpg", "images/listings/hiluxrevo2018/03.jpg", "images/listings/hiluxrevo2018/04.jpg", "images/listings/hiluxrevo2018/05.jpg", "images/listings/hiluxrevo2018/06.jpg", "images/listings/hiluxrevo2018/07.jpg", "images/listings/hiluxrevo2018/08.jpg", "images/listings/hiluxrevo2018/09.jpg", "images/listings/hiluxrevo2018/10.jpg", "images/listings/hiluxrevo2018/11.jpg", "images/listings/hiluxrevo2018/12.jpg", "images/listings/hiluxrevo2018/13.jpg", "images/listings/hiluxrevo2018/14.jpg", "images/listings/hiluxrevo2018/15.jpg", "images/listings/hiluxrevo2018/16.jpg"],
  },
  {
    id: "veh-4runner2025",
    type: "vehiculo",
    title: "Toyota 4Runner 2025 4x4 — Importada, nuevo diseño",
    price: 68000,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Toyota 4Runner línea nueva 4x4 2025, importada, 32,000 millas recorridas, nuevo diseño totalmente, encendido de botón con llave de proximidad. Motor…",
    description:
      "Toyota 4Runner línea nueva 4x4 2025, importada, 32,000 millas recorridas, nuevo diseño totalmente, encendido de botón con llave de proximidad. Motor 2.4 de 4 cilindros gasolina. $68,000, venta únicamente cash de contado.",
    specs: {
      anio: "2025",
      kilometraje: "32,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "2.4, 4 cilindros",
    },
    features: ["Nuevo diseño totalmente, importada", "32,000 millas recorridas", "Encendido de botón con llave de proximidad"],
    images: [],
  },
  {
    id: "veh-front2025",
    type: "vehiculo",
    title: "Nissan Frontier 2025 4x4 — Importada de EE.UU.",
    price: 31500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Nissan Frontier línea nueva 4x4 2025, importada de Estados Unidos, apenas 1,000 millas recorridas, bolsas frontales buenas. Motor 3.8 de 6 cilindros…",
    description:
      "Nissan Frontier línea nueva 4x4 2025, importada de Estados Unidos, apenas 1,000 millas recorridas, bolsas frontales buenas. Motor 3.8 de 6 cilindros gasolina, rines especiales de lujo, doble aire acondicionado, encendido de botón con llave de proximidad, sonido premium, pantalla grande de navegación táctil. $31,500, venta únicamente un solo pago cash. Se recibe vehículo a cuenta a menor valor de mercado.",
    specs: {
      anio: "2025",
      kilometraje: "1,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "3.8, 6 cilindros",
    },
    features: ["Importada de EE.UU., apenas 1,000 millas", "Motor 3.8 V6, rines especiales de lujo", "Doble aire acondicionado", "Encendido de botón, sonido premium, pantalla táctil", "Se recibe vehículo a cuenta a menor valor de mercado"],
    images: ["images/listings/front2025/01.jpg", "images/listings/front2025/02.jpg", "images/listings/front2025/03.jpg", "images/listings/front2025/04.jpg", "images/listings/front2025/05.jpg", "images/listings/front2025/06.jpg"],
  },
  {
    id: "veh-rogue2023",
    type: "vehiculo",
    title: "Nissan Rogue 2023 4x2 — Full extras",
    price: 18000,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Nissan Rogue línea nueva 2023, 4x2 full extras, motor 1.5 turbo súper económico y espaciosa, todas bolsas de aire buenas. $18,000, al crédito con 40%…",
    description:
      "Nissan Rogue línea nueva 2023, 4x2 full extras, motor 1.5 turbo súper económico y espaciosa, todas bolsas de aire buenas. $18,000, al crédito con 40% de prima en efectivo o al contado.",
    specs: {
      anio: "2023",
      kilometraje: "—",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "1.5 turbo",
    },
    features: ["Full extras, todas bolsas de aire buenas", "Motor 1.5 turbo súper económico"],
    images: ["images/listings/rogue2023/01.jpg", "images/listings/rogue2023/02.jpg", "images/listings/rogue2023/03.jpg", "images/listings/rogue2023/04.jpg", "images/listings/rogue2023/05.jpg", "images/listings/rogue2023/06.jpg", "images/listings/rogue2023/07.jpg", "images/listings/rogue2023/08.jpg", "images/listings/rogue2023/09.jpg", "images/listings/rogue2023/10.jpg", "images/listings/rogue2023/11.jpg", "images/listings/rogue2023/12.jpg"],
  },
  {
    id: "veh-outl2022",
    type: "vehiculo",
    title: "Mitsubishi Outlander SE 2022 4x2 — Color negro, 3 filas",
    price: 22500,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Mitsubishi Outlander SE línea nueva 2022, color negro, 4x2, 3 filas de asientos, súper económica y espaciosa, importada de Estados Unidos, 74,000…",
    description:
      "Mitsubishi Outlander SE línea nueva 2022, color negro, 4x2, 3 filas de asientos, súper económica y espaciosa, importada de Estados Unidos, 74,000 millas recorridas. Automática, encendido de botón con llave de proximidad, pantalla de CarPlay y Android Auto. $22,500, venta cash o crédito con EasyCar, 40% de prima, no se acepta vehículo a cuenta.",
    specs: {
      anio: "2022",
      kilometraje: "74,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "2.4, gasolina",
    },
    features: ["Color negro, 3 filas de asientos", "74,000 millas, importada de EE.UU.", "CarPlay y Android Auto", "Encendido de botón con llave de proximidad"],
    images: ["images/listings/outl2022/01.jpg", "images/listings/outl2022/02.jpg", "images/listings/outl2022/03.jpg", "images/listings/outl2022/04.jpg", "images/listings/outl2022/05.jpg", "images/listings/outl2022/06.jpg", "images/listings/outl2022/07.jpg", "images/listings/outl2022/08.jpg", "images/listings/outl2022/09.jpg", "images/listings/outl2022/10.jpg", "images/listings/outl2022/11.jpg"],
  },
  {
    id: "veh-kona2022b",
    type: "vehiculo",
    title: "Hyundai Kona FWD 2022 — Full extras",
    price: 13900,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Hyundai Kona FWD (4x2) 2022 automática, full extras, motor 2.0 de 4 cilindros gasolina, súper económica y espaciosa. Especiales de lujo, aire…",
    description:
      "Hyundai Kona FWD (4x2) 2022 automática, full extras, motor 2.0 de 4 cilindros gasolina, súper económica y espaciosa. Especiales de lujo, aire acondicionado, pantalla de navegación táctil, sonido premium, cámara de retroceso, 76,000 millas recorridas. $13,900 cash o crédito con 40% de prima, cuotas aprox. $350/mes por 5 años.",
    specs: {
      anio: "2022",
      kilometraje: "76,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "2.0, 4 cilindros",
    },
    features: ["76,000 millas, full extras", "Aire acondicionado, pantalla táctil, sonido premium", "Cámara de retroceso"],
    images: [],
  },
  {
    id: "veh-corolla2021",
    type: "vehiculo",
    title: "Toyota Corolla 2021 — Línea nueva",
    price: 13900,
    location: "Coordinar por WhatsApp",
    operacion: "Venta",
    summary: "Toyota Corolla línea nueva 2021, motor 1.8 de 4 cilindros gasolina, súper económico y espacioso, importado de Estados Unidos, 76,000 millas…",
    description:
      "Toyota Corolla línea nueva 2021, motor 1.8 de 4 cilindros gasolina, súper económico y espacioso, importado de Estados Unidos, 76,000 millas recorridas. Ventanas eléctricas, aire acondicionado, pantalla de navegación táctil, cámara de retroceso, a toda revisión mecánica. $13,900 cash o crédito con EasyCar/CreditCar, 40% de prima.",
    specs: {
      anio: "2021",
      kilometraje: "76,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "1.8, 4 cilindros",
    },
    features: ["76,000 millas, importado de EE.UU.", "Ventanas eléctricas, aire acondicionado", "Pantalla táctil, cámara de retroceso"],
    images: ["images/listings/corolla2021/01.jpg", "images/listings/corolla2021/02.jpg", "images/listings/corolla2021/03.jpg", "images/listings/corolla2021/04.jpg", "images/listings/corolla2021/05.jpg", "images/listings/corolla2021/06.jpg", "images/listings/corolla2021/07.jpg", "images/listings/corolla2021/08.jpg", "images/listings/corolla2021/09.jpg", "images/listings/corolla2021/10.jpg", "images/listings/corolla2021/11.jpg", "images/listings/corolla2021/12.jpg", "images/listings/corolla2021/13.jpg", "images/listings/corolla2021/14.jpg"],
  },
  {
    id: "veh-versa2017",
    type: "vehiculo",
    title: "Nissan Versa 2017 — Precio fijo",
    price: 6500,
    location: "Santa Tecla",
    operacion: "Venta",
    summary: "Nissan Versa 2017, todas las bolsas de aire buenas, importado de Estados Unidos, motor 1.6 súper económico y espacioso, 96,000 millas recorridas, a…",
    description:
      "Nissan Versa 2017, todas las bolsas de aire buenas, importado de Estados Unidos, motor 1.6 súper económico y espacioso, 96,000 millas recorridas, a toda revisión mecánica. No se aceptan cambios ni carro a cuenta, solo venta cash. $6,500 dólares precio fijo, o al crédito con 40% de prima, cuotas aprox. $250/mes por 5 años. Se muestra en oficina de Santa Tecla.",
    specs: {
      anio: "2017",
      kilometraje: "96,000 millas",
      transmision: "Automática",
      combustible: "Gasolina",
      motor: "1.6",
    },
    features: ["96,000 millas, importado de EE.UU.", "Todas bolsas de aire buenas", "A toda revisión mecánica, precio fijo"],
    images: ["images/listings/versa2017/01.jpg", "images/listings/versa2017/02.jpg", "images/listings/versa2017/03.jpg", "images/listings/versa2017/04.jpg", "images/listings/versa2017/05.jpg", "images/listings/versa2017/06.jpg"],
  },

];